"""
Scheduling Analytics Models

Database models for the scheduling intelligence continuous learning system.

Tables:
- scheduling_insights: Stored insights generated by the scheduling intelligence engine
- appointment_outcomes: Outcome tracking for appointments (conversion, revenue, timing)

These models store the output of SQL-based statistical analysis to avoid
recomputing expensive aggregations on every request.
"""

from datetime import datetime, timezone
from sqlalchemy import (
    Column, Integer, String, Boolean, DateTime, Date,
    Text, ForeignKey, JSON, Float, Numeric, Index,
)
from sqlalchemy.orm import relationship

from db import Base


class SchedulingInsight(Base):
    """
    Cached scheduling insights generated by the intelligence engine.

    Each insight represents a statistically significant pattern discovered
    from historical appointment data (e.g., "Tuesday 10am has 85% show rate").
    Insights have a validity window and confidence score.
    """
    __tablename__ = "scheduling_insights"
    __table_args__ = (
        Index('ix_sched_insight_org_type', 'organization_id', 'insight_type'),
        Index('ix_sched_insight_valid', 'valid_from', 'valid_to'),
        {'extend_existing': True},
    )

    id = Column(Integer, primary_key=True, index=True)
    organization_id = Column(Integer, ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True)

    # Insight classification
    insight_type = Column(String(80), nullable=False, index=True)
    # Types: time_slot_performance, lo_lead_match, no_show_pattern,
    #        script_performance, followup_timing, duration_prediction,
    #        conversion_trend, weekly_digest

    # Insight content
    title = Column(String(255), nullable=False)
    description = Column(Text)
    data = Column(JSON, nullable=False, default=dict)  # Structured payload

    # Statistical confidence
    confidence = Column(Float, nullable=False, default=0.0)  # 0.0-1.0
    sample_size = Column(Integer, default=0)

    # Validity window
    valid_from = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))
    valid_to = Column(DateTime, nullable=True)  # Null = no expiration

    # Targeting (optional: who does this insight apply to?)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True)  # Specific LO
    lead_source = Column(String(100), nullable=True)  # Specific lead source
    appointment_type = Column(String(80), nullable=True)  # Specific meeting type

    # Status
    is_active = Column(Boolean, default=True)
    superseded_by_id = Column(Integer, ForeignKey("scheduling_insights.id"), nullable=True)

    # Metadata
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

    # Relationships
    superseded_by = relationship("SchedulingInsight", remote_side=[id])


class AppointmentOutcome(Base):
    """
    Tracks the downstream outcome of an appointment for learning purposes.

    Links an appointment to its business result: did the client show up?
    Did they convert to a loan application? Did they fund? How much revenue?
    This data feeds the continuous learning system.
    """
    __tablename__ = "appointment_outcomes"
    __table_args__ = (
        Index('ix_appt_outcome_org', 'organization_id'),
        Index('ix_appt_outcome_appt', 'appointment_id'),
        Index('ix_appt_outcome_lo', 'lo_user_id'),
        Index('ix_appt_outcome_date', 'appointment_date'),
        {'extend_existing': True},
    )

    id = Column(Integer, primary_key=True, index=True)
    organization_id = Column(Integer, ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True)

    # Link to appointment
    appointment_id = Column(Integer, ForeignKey("scheduler_appointments.id"), nullable=False, index=True)

    # Outcome tracking
    outcome = Column(String(50), nullable=False, index=True)
    # Values: showed, no_show, cancelled, rescheduled

    # Conversion tracking
    conversion_stage = Column(String(80), nullable=True)
    # Values: none, application_started, submitted, approved, funded
    converted_to_loan_id = Column(Integer, ForeignKey("loans.id"), nullable=True)
    revenue = Column(Numeric(18, 2), nullable=True)  # Revenue if funded

    # Time tracking
    appointment_date = Column(Date, nullable=False, index=True)
    appointment_hour = Column(Integer, nullable=False)  # 0-23
    appointment_day_of_week = Column(Integer, nullable=False)  # 0=Mon, 6=Sun
    time_to_conversion_days = Column(Integer, nullable=True)  # Days from appointment to conversion

    # Context at time of appointment
    lo_user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    lead_id = Column(Integer, ForeignKey("leads.id"), nullable=True)
    lead_source = Column(String(100), nullable=True)
    lead_score = Column(Integer, nullable=True)
    appointment_type = Column(String(80), nullable=True)
    meeting_mode = Column(String(50), nullable=True)  # video, phone, in_person
    booked_via = Column(String(50), nullable=True)  # ai_voice, web, manual

    # Reminder effectiveness
    reminder_sent = Column(Boolean, default=False)
    reminder_acknowledged = Column(Boolean, default=False)

    # Duration tracking
    scheduled_duration_minutes = Column(Integer, nullable=True)
    actual_duration_minutes = Column(Integer, nullable=True)

    # Rescheduling history
    reschedule_count = Column(Integer, default=0)
    was_rescheduled = Column(Boolean, default=False)

    # Metadata
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))
