#!/bin/bash

API_BASE="https://api.perenniaai.com"

echo "🔧 Applying MUM Client Fields Migration to Production"
echo "=================================================="
echo ""
echo "This migration will add the following columns:"
echo "  - mum_clients: email, phone, notes, close_date, team members, etc."
echo "  - activities: mum_client_id"
echo ""
echo "Please log into the application and run this command in your browser's console:"
echo ""
echo "fetch('$API_BASE/api/v1/migrations/add-mum-client-fields', {"
echo "  method: 'POST',"
echo "  headers: {"
echo "    'Authorization': 'Bearer ' + localStorage.getItem('token'),"
echo "    'Content-Type': 'application/json'"
echo "  }"
echo "}).then(r => r.json()).then(d => {"
echo "  console.log('Migration Result:', d);"
echo "  if (d.success) {"
echo "    alert('✅ Migration successful! Added ' + d.added_columns.length + ' columns.');"
echo "  } else {"
echo "    alert('Migration result: ' + d.message);"
echo "  }"
echo "});"
echo ""
echo "=================================================="
echo ""
echo "Steps:"
echo "1. Open https://api.perenniaai.com in your browser"
echo "2. Log in with your credentials"
echo "3. Press F12 to open Developer Console"
echo "4. Paste the command above and press Enter"
echo ""
