/**
 * Purchase Application - Declaration Questions
 * Purchase-specific declaration questions used in the wizard flow.
 * Each question has conditional show/hide logic based on previous answers.
 */

export const DECLARATION_QUESTIONS = [
  {
    id: 'borrower_count',
    question: 'How many people will be on this loan application?',
    type: 'choice',
    options: [
      { value: '1', label: 'Just me', icon: 'user' },
      { value: '2', label: 'Two of us', icon: 'users' },
      { value: '3', label: 'Three people', icon: 'family' },
      { value: '4+', label: 'Four or more', icon: 'family' },
    ],
    hint: 'This helps us know how many borrowers to include in the application.',
  },
  {
    id: 'co_borrower_relationship',
    question: 'What is your relationship to the other borrower(s)?',
    type: 'choice',
    options: [
      { value: 'spouse', label: 'Spouse/Partner', icon: 'heart' },
      { value: 'relative', label: 'Family member', icon: 'family' },
      { value: 'friend', label: 'Friend/Non-relative', icon: 'users' },
      { value: 'business_partner', label: 'Business partner', icon: 'briefcase' },
    ],
    hint: 'This helps us understand the borrower structure.',
    showIf: { field: 'borrower_count', values: ['2', '3', '4+'] },
  },
  {
    id: 'citizenship_status',
    question: 'What is your citizenship status?',
    type: 'choice',
    options: [
      { value: 'us_citizen', label: 'U.S. Citizen', icon: 'check' },
      { value: 'permanent_resident', label: 'Permanent Resident (Green Card)', icon: 'document' },
      { value: 'non_permanent_resident', label: 'Non-Permanent Resident (Visa)', icon: 'globe' },
      { value: 'non_resident', label: 'Non-Resident Alien', icon: 'globe' },
    ],
    hint: 'This helps determine which loan programs you qualify for.',
  },
  {
    id: 'first_time_buyer',
    question: 'Is this your first home purchase?',
    type: 'choice',
    options: [
      { value: 'yes', label: 'Yes, first-time buyer!', icon: 'celebration' },
      { value: 'no', label: 'No, I\'ve bought before', icon: 'home' },
    ],
    hint: 'First-time buyers may qualify for special programs!',
  },
  {
    id: 'desired_state',
    question: 'What state are you looking to buy in?',
    type: 'state_select',
    hint: 'This helps us find state-specific programs and lenders.',
  },
  {
    id: 'desired_city',
    question: 'What city or area are you looking to buy in?',
    type: 'text',
    placeholder: 'e.g., Austin, Denver metro, Orange County',
    hint: 'This helps us connect you with local experts.',
  },
  {
    id: 'previous_home_status',
    question: 'What happened to your previous home?',
    type: 'choice',
    options: [
      { value: 'sold', label: 'Sold it', icon: 'check' },
      { value: 'second_home', label: 'Keeping as second home', icon: 'home' },
      { value: 'renting_out', label: 'Renting it out', icon: 'dollarSign' },
      { value: 'foreclosure', label: 'Lost to foreclosure/short sale', icon: 'alertTriangle' },
    ],
    hint: 'This affects your loan options and what we need to document.',
    showIf: { field: 'first_time_buyer', values: ['no'] },
  },
  {
    id: 'previous_home_mortgage',
    question: 'Is there a mortgage on this property?',
    type: 'choice',
    options: [
      { value: 'yes', label: 'Yes, there is a mortgage', icon: 'document' },
      { value: 'no', label: 'No, owned free and clear', icon: 'check' },
    ],
    hint: 'We\'ll need the current mortgage statement if there is one.',
    showIf: { field: 'previous_home_status', values: ['second_home', 'renting_out'] },
  },
  {
    id: 'foreclosure_timeline',
    question: 'When did the foreclosure or short sale occur?',
    type: 'choice',
    options: [
      { value: 'less_than_2_years', label: 'Less than 2 years ago', icon: 'clock' },
      { value: '2_to_4_years', label: '2-4 years ago', icon: 'clock' },
      { value: '4_to_7_years', label: '4-7 years ago', icon: 'calendar' },
      { value: 'more_than_7_years', label: 'More than 7 years ago', icon: 'calendar' },
    ],
    hint: 'Different loan programs have different waiting periods after foreclosure.',
    showIf: { field: 'previous_home_status', values: ['foreclosure'] },
  },
  {
    id: 'rental_income_previous',
    question: 'How much rental income do you receive monthly from the property?',
    type: 'currency',
    placeholder: 'Monthly rental income',
    hint: 'This rental income can help qualify you for more home.',
    showIf: { field: 'previous_home_status', values: ['renting_out'] },
  },
  {
    id: 'marital_status',
    question: 'Are you married?',
    type: 'choice',
    options: [
      { value: 'married', label: 'Yes, married', icon: 'heart' },
      { value: 'single', label: 'Single', icon: 'user' },
      { value: 'divorced', label: 'Divorced', icon: 'document' },
      { value: 'separated', label: 'Separated', icon: 'users' },
      { value: 'widowed', label: 'Widowed', icon: 'heart' },
    ],
    unlocks: ['spouse_section'],
    hideIf: { field: 'co_borrower_relationship', values: ['spouse'] },
  },
  {
    id: 'spouse_on_loan',
    question: 'Will your spouse be on the loan application?',
    type: 'choice',
    options: [
      { value: 'yes', label: 'Yes, both of us', icon: 'users' },
      { value: 'no', label: 'No, just me', icon: 'user' },
    ],
    hint: 'In community property states, spouse income/debts may still be considered.',
    showIf: { field: 'marital_status', values: ['married'] },
  },
  {
    id: 'divorce_finalized',
    question: 'Is your divorce finalized?',
    type: 'choice',
    options: [
      { value: 'yes', label: 'Yes, finalized', icon: 'check' },
      { value: 'pending', label: 'Still pending', icon: 'clock' },
    ],
    hint: 'A pending divorce may require additional documentation.',
    showIf: { field: 'marital_status', values: ['divorced', 'separated'] },
  },
  {
    id: 'child_support_alimony',
    question: 'Do you receive or pay child support or alimony?',
    type: 'choice',
    options: [
      { value: 'receive', label: 'I receive payments', icon: 'dollarSign' },
      { value: 'pay', label: 'I make payments', icon: 'creditCard' },
      { value: 'both', label: 'Both receive and pay', icon: 'refresh' },
      { value: 'neither', label: 'Neither', icon: 'arrowRight' },
    ],
    hint: 'This income/expense will be considered in your loan qualification.',
    showIf: { field: 'marital_status', values: ['divorced', 'separated'] },
  },
  {
    id: 'support_amount_received',
    question: 'How much do you receive per month in child support/alimony?',
    type: 'currency',
    placeholder: 'Monthly amount received',
    hint: 'This can count as qualifying income if documented.',
    showIf: { field: 'child_support_alimony', values: ['receive', 'both'] },
  },
  {
    id: 'support_duration_received',
    question: 'How long have you been receiving this income?',
    type: 'choice',
    options: [
      { value: 'less_than_6_months', label: 'Less than 6 months', icon: 'clock' },
      { value: '6_to_12_months', label: '6-12 months', icon: 'clock' },
      { value: '1_to_3_years', label: '1-3 years', icon: 'calendar' },
      { value: 'more_than_3_years', label: 'More than 3 years', icon: 'calendar' },
    ],
    hint: 'Income must typically continue for at least 3 more years to count.',
    showIf: { field: 'child_support_alimony', values: ['receive', 'both'] },
  },
  {
    id: 'support_amount_paid',
    question: 'How much do you pay per month in child support/alimony?',
    type: 'currency',
    placeholder: 'Monthly amount paid',
    hint: 'This will be factored into your debt-to-income ratio.',
    showIf: { field: 'child_support_alimony', values: ['pay', 'both'] },
  },
  {
    id: 'support_type_paid',
    question: 'What type of payments are you making?',
    type: 'choice',
    options: [
      { value: 'child_support', label: 'Child Support only', icon: 'family' },
      { value: 'alimony', label: 'Alimony/Spousal Support only', icon: 'heart' },
      { value: 'both', label: 'Both Child Support and Alimony', icon: 'users' },
    ],
    hint: 'Different payment types may have different documentation requirements.',
    showIf: { field: 'child_support_alimony', values: ['pay', 'both'] },
  },
  {
    id: 'support_duration_paid',
    question: 'How long will you continue making these payments?',
    type: 'choice',
    options: [
      { value: 'less_than_1_year', label: 'Less than 1 year', icon: 'clock' },
      { value: '1_to_3_years', label: '1-3 years', icon: 'calendar' },
      { value: '3_to_5_years', label: '3-5 years', icon: 'calendar' },
      { value: 'more_than_5_years', label: 'More than 5 years', icon: 'calendar' },
      { value: 'until_child_18', label: 'Until child turns 18', icon: 'family' },
    ],
    hint: 'Payments ending within 10 months may not be counted against you.',
    showIf: { field: 'child_support_alimony', values: ['pay', 'both'] },
  },
  {
    id: 'support_type_received',
    question: 'What type of payments are you receiving?',
    type: 'choice',
    options: [
      { value: 'child_support', label: 'Child Support only', icon: 'family' },
      { value: 'alimony', label: 'Alimony/Spousal Support only', icon: 'heart' },
      { value: 'both', label: 'Both Child Support and Alimony', icon: 'users' },
    ],
    hint: 'Different payment types may count differently as qualifying income.',
    showIf: { field: 'child_support_alimony', values: ['receive', 'both'] },
  },
  {
    id: 'support_years_remaining',
    question: 'How many more years will you receive these payments?',
    type: 'choice',
    options: [
      { value: 'less_than_3_years', label: 'Less than 3 years', icon: 'clock' },
      { value: '3_to_5_years', label: '3-5 years', icon: 'calendar' },
      { value: '5_to_10_years', label: '5-10 years', icon: 'calendar' },
      { value: 'more_than_10_years', label: 'More than 10 years', icon: 'calendar' },
    ],
    hint: 'Income must typically continue for at least 3 more years to count.',
    showIf: { field: 'child_support_alimony', values: ['receive', 'both'] },
  },
  {
    id: 'property_interest',
    question: 'Do you have interest in any other real estate property?',
    type: 'choice',
    options: [
      { value: 'yes', label: 'Yes, I own property', icon: 'home' },
      { value: 'no', label: 'No other properties', icon: 'arrowRight' },
    ],
    hint: 'This includes properties you own, co-own, or have ownership interest in.',
    showIf: { field: 'first_time_buyer', values: ['no'] },
  },
  {
    id: 'property_interest_address',
    question: 'What is the address of the property you have interest in?',
    type: 'address',
    placeholder: 'Enter property address',
    hint: 'We\'ll need details about this property for your application.',
    showIf: { field: 'property_interest', values: ['yes'] },
  },
  {
    id: 'veteran',
    question: 'Have you or your spouse served in the military?',
    type: 'choice',
    options: [
      { value: 'yes', label: 'Yes, I\'m a Veteran', icon: 'medal' },
      { value: 'active', label: 'Currently Active Duty', icon: 'star' },
      { value: 'spouse', label: 'My spouse served', icon: 'heart' },
      { value: 'no', label: 'No military service', icon: 'arrowRight' },
    ],
    hint: 'Veterans can get VA loans with $0 down!',
  },
  {
    id: 'va_loan_before',
    question: 'Have you used a VA loan before?',
    type: 'choice',
    options: [
      { value: 'yes_paid_off', label: 'Yes, paid it off', icon: 'check' },
      { value: 'yes_still_have', label: 'Yes, still have it', icon: 'home' },
      { value: 'no', label: 'No, first VA loan', icon: 'star' },
    ],
    hint: 'You can use your VA benefit multiple times!',
    showIf: { field: 'veteran', values: ['yes', 'active', 'spouse'] },
  },
  {
    id: 'va_disability',
    question: 'Do you have a VA disability rating?',
    type: 'choice',
    options: [
      { value: 'yes_10_plus', label: 'Yes, 10% or higher', icon: 'shield' },
      { value: 'pending', label: 'Claim pending', icon: 'clock' },
      { value: 'no', label: 'No disability rating', icon: 'arrowRight' },
    ],
    hint: '10%+ disability rating waives the VA funding fee - saves thousands!',
    showIf: { field: 'veteran', values: ['yes', 'active'] },
  },
  {
    id: 'self_employed',
    question: 'Are you self-employed or own a business?',
    type: 'choice',
    options: [
      { value: 'yes', label: 'Yes, self-employed', icon: 'building' },
      { value: 'side_business', label: 'I have a side business', icon: 'briefcase' },
      { value: 'no', label: 'No, I\'m a W-2\'d employee', icon: 'tie' },
    ],
    hint: 'This helps us know what income documents you\'ll need.',
  },
  {
    id: 'business_years',
    question: 'How long have you been self-employed?',
    type: 'choice',
    options: [
      { value: 'less_than_1_year', label: 'Less than 1 year', icon: 'clock' },
      { value: '1_to_2_years', label: '1-2 years', icon: 'calendar' },
      { value: 'more_than_2_years', label: 'More than 2 years', icon: 'check' },
    ],
    hint: 'Most loan programs require 2 years of self-employment history.',
    showIf: { field: 'self_employed', values: ['yes'] },
  },
  {
    id: 'business_type',
    question: 'What type of business do you have?',
    type: 'choice',
    options: [
      { value: 'sole_proprietor', label: 'Sole proprietor', icon: 'user' },
      { value: 'llc', label: 'LLC', icon: 'building' },
      { value: 's_corp', label: 'S-Corp', icon: 'briefcase' },
      { value: 'c_corp', label: 'C-Corp', icon: 'building' },
      { value: 'partnership', label: 'Partnership', icon: 'users' },
    ],
    hint: 'This determines what tax documents we\'ll need.',
    showIf: { field: 'self_employed', values: ['yes', 'side_business'] },
  },
  {
    id: 'prior_year_taxes_filed',
    question: 'Have you filed your prior year tax returns?',
    type: 'choice',
    options: [
      { value: 'yes', label: 'Yes, taxes are filed', icon: 'check' },
      { value: 'no', label: 'No, not filed yet', icon: 'clock' },
      { value: 'extension', label: 'Filed an extension', icon: 'calendar' },
    ],
    hint: 'If taxes are not yet filed, we\'ll need a year-to-date Profit & Loss statement.',
    showIf: { field: 'self_employed', values: ['yes', 'side_business'] },
  },
  {
    id: 'write_off_expenses',
    question: 'Do you write off most expenses to minimize taxable income?',
    type: 'choice',
    options: [
      { value: 'yes', label: 'Yes, I maximize deductions', icon: 'trendDown' },
      { value: 'some', label: 'Some, but I show decent income', icon: 'balance' },
      { value: 'no', label: 'No, I show most of my income', icon: 'trendUp' },
    ],
    hint: 'Self-employed income is based on your adjusted gross income after expenses. If you write off heavily, we may need 12 months of business bank statements.',
    showIf: { field: 'self_employed', values: ['yes', 'side_business'] },
  },
  {
    id: 'irs_balance_owed',
    question: 'Do you have an outstanding balance owed to the IRS?',
    type: 'choice',
    options: [
      { value: 'yes', label: 'Yes, I owe the IRS', icon: 'alertTriangle' },
      { value: 'payment_plan', label: 'Yes, but on a payment plan', icon: 'clipboard' },
      { value: 'no', label: 'No outstanding balance', icon: 'check' },
    ],
    hint: 'Having a balance doesn\'t disqualify you - we just need to know.',
  },
  {
    id: 'irs_amount_owed',
    question: "What's the monthly payment?",
    type: 'currency',
    placeholder: '0',
    hint: 'This helps us understand your full financial picture.',
    showIf: { field: 'irs_balance_owed', values: ['yes', 'payment_plan'] },
  },
  {
    id: 'irs_payment_current',
    question: 'Are you current on your IRS payment plan?',
    type: 'choice',
    options: [
      { value: 'yes', label: 'Yes, fully current', icon: 'check' },
      { value: 'behind', label: 'Behind on payments', icon: 'alertTriangle' },
    ],
    hint: 'Being current on payments is usually required for loan approval.',
    showIf: { field: 'irs_balance_owed', values: ['payment_plan'] },
  },
  {
    id: 'recent_credit_applications',
    question: 'Have you applied for any credit in the past 3 months?',
    type: 'choice',
    options: [
      { value: 'yes', label: 'Yes, I applied recently', icon: 'creditCard' },
      { value: 'no', label: 'No recent applications', icon: 'check' },
    ],
    hint: 'Car loans, credit cards, personal loans, etc. Recent inquiries can affect your score.',
  },
  {
    id: 'credit_application_type',
    question: 'What type of credit did you apply for?',
    type: 'choice',
    options: [
      { value: 'auto_loan', label: 'Auto loan', icon: 'car' },
      { value: 'credit_card', label: 'Credit card', icon: 'creditCard' },
      { value: 'personal_loan', label: 'Personal loan', icon: 'dollarSign' },
      { value: 'other', label: 'Other', icon: 'document' },
    ],
    hint: 'Recent auto loans can significantly impact your debt-to-income ratio.',
    showIf: { field: 'recent_credit_applications', values: ['yes'] },
  },
  {
    id: 'credit_application_approved',
    question: 'Was the credit application approved?',
    type: 'choice',
    options: [
      { value: 'yes', label: 'Yes, approved', icon: 'check' },
      { value: 'pending', label: 'Still pending', icon: 'clock' },
      { value: 'no', label: 'No, denied', icon: 'x' },
    ],
    hint: 'If approved, we\'ll need to factor in the new payment.',
    showIf: { field: 'recent_credit_applications', values: ['yes'] },
  },
  {
    id: 'gift_funds',
    question: 'Will you use gift funds for your down payment?',
    type: 'choice',
    options: [
      { value: 'yes', label: 'Yes, receiving a gift', icon: 'gift' },
      { value: 'maybe', label: 'Maybe, not sure yet', icon: 'helpCircle' },
      { value: 'no', label: 'No, using my own funds', icon: 'dollarSign' },
    ],
    hint: 'Gift funds from family are totally okay!',
  },
  {
    id: 'gift_amount',
    question: 'How much gift money will you receive?',
    type: 'currency',
    placeholder: 'Gift amount',
    hint: 'We\'ll need a gift letter from the donor.',
    showIf: { field: 'gift_funds', values: ['yes'] },
  },
  {
    id: 'gift_donor',
    question: 'Who is providing the gift?',
    type: 'choice',
    options: [
      { value: 'parent', label: 'Parent', icon: 'family' },
      { value: 'grandparent', label: 'Grandparent', icon: 'family' },
      { value: 'sibling', label: 'Sibling', icon: 'users' },
      { value: 'other_relative', label: 'Other relative', icon: 'users' },
      { value: 'non_relative', label: 'Non-relative', icon: 'user' },
    ],
    hint: 'Gift rules vary based on relationship and loan type.',
    showIf: { field: 'gift_funds', values: ['yes'] },
  },
  {
    id: 'found_property',
    question: 'Have you found a property yet?',
    type: 'choice',
    options: [
      { value: 'yes', label: 'Yes, under contract', icon: 'document' },
      { value: 'looking', label: 'Still shopping', icon: 'search' },
      { value: 'pre_approval', label: 'Just getting pre-approved', icon: 'check' },
    ],
  },
  {
    id: 'closing_date',
    question: 'When is your target closing date?',
    type: 'choice',
    options: [
      { value: 'less_than_30', label: 'Less than 30 days', icon: 'clock' },
      { value: '30_to_45', label: '30-45 days', icon: 'calendar' },
      { value: '45_to_60', label: '45-60 days', icon: 'calendar' },
      { value: 'more_than_60', label: 'More than 60 days', icon: 'calendar' },
    ],
    hint: 'Knowing your timeline helps us prioritize appropriately.',
    showIf: { field: 'found_property', values: ['yes'] },
  },
  {
    id: 'working_with_agent',
    question: 'Are you working with a real estate agent?',
    type: 'choice',
    options: [
      { value: 'yes', label: 'Yes, have an agent', icon: 'users' },
      { value: 'no', label: 'Not yet', icon: 'search' },
    ],
    hint: 'We can recommend great agents in your area if needed.',
  },
  {
    id: 'agent_info',
    question: 'Tell us about your real estate agent',
    type: 'agent_info',
    hint: 'Start typing to search our partner network, or enter their details manually.',
    showIf: { field: 'working_with_agent', values: ['yes'] },
  },
  {
    id: 'credit_issues',
    question: 'Have you had any credit challenges in the past 2 years?',
    type: 'choice',
    options: [
      { value: 'none', label: 'No issues', icon: 'check' },
      { value: 'late_payments', label: 'Late payments', icon: 'clock' },
      { value: 'collections', label: 'Collections/charge-offs', icon: 'alertTriangle' },
      { value: 'bankruptcy', label: 'Bankruptcy', icon: 'document' },
    ],
    hint: 'Being upfront helps us find the right program for you.',
  },
  {
    id: 'bankruptcy_type',
    question: 'What type of bankruptcy did you file?',
    type: 'choice',
    options: [
      { value: 'chapter_7', label: 'Chapter 7', icon: 'document' },
      { value: 'chapter_13', label: 'Chapter 13', icon: 'document' },
      { value: 'chapter_12', label: 'Chapter 12 (Farm/Fisherman)', icon: 'document' },
    ],
    hint: 'Different waiting periods apply for each type.',
    showIf: { field: 'credit_issues', values: ['bankruptcy'] },
  },
  {
    id: 'bankruptcy_discharge_ch7',
    question: 'When was your Chapter 7 bankruptcy discharged?',
    type: 'choice',
    options: [
      { value: 'less_than_2_years', label: 'Less than 2 years ago', icon: 'clock' },
      { value: '2_to_4_years', label: '2-4 years ago', icon: 'calendar' },
      { value: '4_to_7_years', label: '4-7 years ago', icon: 'calendar' },
      { value: '8_years_or_more', label: '8 years ago or more', icon: 'check' },
    ],
    hint: 'Chapter 7 typically has a 2-4 year waiting period depending on loan type.',
    showIf: { field: 'bankruptcy_type', values: ['chapter_7'] },
  },
  {
    id: 'chapter_13_status',
    question: 'What is the status of your Chapter 13 bankruptcy?',
    type: 'choice',
    options: [
      { value: 'active_paying', label: 'Actively paying to trustee', icon: 'clock' },
      { value: 'completed', label: 'Completed/Discharged', icon: 'check' },
    ],
    hint: 'Active Chapter 13 plans may still qualify with court approval.',
    showIf: { field: 'bankruptcy_type', values: ['chapter_13'] },
  },
  {
    id: 'bankruptcy_discharge_ch13',
    question: 'When was your Chapter 13 bankruptcy discharged?',
    type: 'choice',
    options: [
      { value: 'less_than_2_years', label: 'Less than 2 years ago', icon: 'clock' },
      { value: '2_to_4_years', label: '2-4 years ago', icon: 'calendar' },
      { value: 'more_than_4_years', label: 'More than 4 years ago', icon: 'calendar' },
    ],
    hint: 'Chapter 13 discharge typically requires 2-4 year waiting period.',
    showIf: { field: 'chapter_13_status', values: ['completed'] },
  },
  {
    id: 'chapter_12_status',
    question: 'What is the status of your Chapter 12 bankruptcy?',
    type: 'choice',
    options: [
      { value: 'active_paying', label: 'Actively in repayment plan', icon: 'clock' },
      { value: 'completed', label: 'Completed/Discharged', icon: 'check' },
    ],
    hint: 'Chapter 12 bankruptcies require payment history and court documentation.',
    showIf: { field: 'bankruptcy_type', values: ['chapter_12'] },
  },
];
