#!/usr/bin/env python3
"""
Coverage Threshold Enforcement Script

Enforces per-module coverage thresholds beyond pytest-cov's global fail_under.
Run after pytest --cov to check module-specific coverage.

Usage:
    pytest --cov=. --cov-report=json
    python scripts/check_coverage.py

Thresholds:
    - Security modules (auth/): 95%
    - Financial calculations: 95%
    - API endpoints (routes/): 90%
    - Services: 85%
    - Overall: 85%
"""

import json
import sys
from pathlib import Path


# Per-module coverage thresholds
THRESHOLDS = {
    # Security-critical modules - highest threshold
    "auth/": 95.0,
    "middleware/csrf": 95.0,
    "middleware/security": 95.0,
    "security_middleware": 95.0,

    # Financial calculations
    "services/pricing": 95.0,
    "services/rate_lock": 95.0,
    "services/profitability": 95.0,

    # API endpoints
    "routes/": 90.0,
    "routers/": 90.0,

    # Core services
    "services/": 85.0,
    "agents/": 85.0,

    # Infrastructure (lower threshold)
    "database/": 80.0,
    "core/": 80.0,
    "middleware/": 85.0,
}

# Minimum overall coverage
OVERALL_THRESHOLD = 85.0


def load_coverage_report(path: str = "coverage.json") -> dict:
    """Load coverage.json generated by pytest-cov."""
    coverage_path = Path(path)
    if not coverage_path.exists():
        print(f"Error: {path} not found. Run pytest --cov-report=json first.")
        sys.exit(1)

    with open(coverage_path) as f:
        return json.load(f)


def get_module_coverage(data: dict, module_prefix: str) -> tuple[float, list[str]]:
    """Calculate coverage for files matching a module prefix."""
    files = data.get("files", {})
    matching_files = []
    total_covered = 0
    total_statements = 0

    for file_path, file_data in files.items():
        if module_prefix in file_path:
            matching_files.append(file_path)
            summary = file_data.get("summary", {})
            total_covered += summary.get("covered_lines", 0)
            total_statements += summary.get("num_statements", 0)

    if total_statements == 0:
        return 100.0, matching_files  # No statements = pass

    coverage = (total_covered / total_statements) * 100
    return coverage, matching_files


def check_thresholds(data: dict) -> list[str]:
    """Check all module thresholds and return failures."""
    failures = []

    print("\n" + "=" * 60)
    print("Module Coverage Report")
    print("=" * 60)

    for module_prefix, threshold in THRESHOLDS.items():
        coverage, files = get_module_coverage(data, module_prefix)

        if not files:
            print(f"  {module_prefix:<30} No files found")
            continue

        status = "PASS" if coverage >= threshold else "FAIL"
        icon = "✓" if coverage >= threshold else "✗"

        print(f"  {icon} {module_prefix:<28} {coverage:>6.1f}% (threshold: {threshold}%)")

        if coverage < threshold:
            failures.append(
                f"{module_prefix}: {coverage:.1f}% < {threshold}% threshold"
            )

    # Check overall coverage
    totals = data.get("totals", {})
    overall = totals.get("percent_covered", 0)

    print("\n" + "-" * 60)
    overall_status = "PASS" if overall >= OVERALL_THRESHOLD else "FAIL"
    overall_icon = "✓" if overall >= OVERALL_THRESHOLD else "✗"
    print(f"  {overall_icon} {'Overall':<28} {overall:>6.1f}% (threshold: {OVERALL_THRESHOLD}%)")

    if overall < OVERALL_THRESHOLD:
        failures.append(f"Overall: {overall:.1f}% < {OVERALL_THRESHOLD}% threshold")

    print("=" * 60 + "\n")

    return failures


def main():
    """Main entry point."""
    print("\nPerennia CRM - Coverage Threshold Check")

    data = load_coverage_report()
    failures = check_thresholds(data)

    if failures:
        print("Coverage check FAILED:")
        for failure in failures:
            print(f"  - {failure}")
        print("\nPlease add tests to improve coverage in the failing modules.")
        sys.exit(1)
    else:
        print("Coverage check PASSED - All thresholds met!")
        sys.exit(0)


if __name__ == "__main__":
    main()
