"""
04-migrations/env.py

Async-aware Alembic env.py. Replaces the template generated by `alembic init -t async`
with Perennia-specific wiring: loads settings, normalizes Railway's postgres:// URL,
and autogenerates against the full app metadata.

Drop-in: backend/alembic/env.py
"""

import asyncio
import logging
import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

# ----- Import all models so autogenerate sees every table --------------------
# Import Base from the models package. Wildcard-import to trigger registration.
from app.core.db import Base  # noqa: F401
from app.models import *  # noqa: F401, F403

target_metadata = Base.metadata

# ----- Alembic config --------------------------------------------------------

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

logger = logging.getLogger("alembic.env")

# Normalize DATABASE_URL from Railway-style to async driver
db_url = os.environ.get("DATABASE_URL", config.get_main_option("sqlalchemy.url", ""))
if db_url.startswith("postgres://"):
    db_url = db_url.replace("postgres://", "postgresql+asyncpg://", 1)
elif db_url.startswith("postgresql://") and "+asyncpg" not in db_url:
    db_url = db_url.replace("postgresql://", "postgresql+asyncpg://", 1)

if not db_url:
    raise RuntimeError("DATABASE_URL not set and no sqlalchemy.url in alembic.ini")

config.set_main_option("sqlalchemy.url", db_url)


# ----- Migration helpers -----------------------------------------------------

def include_object(object, name, type_, reflected, compare_to):
    """
    Filter what gets included in autogenerate diffs.
    Skip pgvector internal tables and anything we manage externally.
    """
    if type_ == "table" and name in {"alembic_version", "pg_stat_statements"}:
        return False
    # Skip pgvector index types — they are managed in raw SQL migrations
    return True


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (generates SQL, doesn't connect)."""
    context.configure(
        url=db_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
        compare_type=True,
        compare_server_default=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        include_object=include_object,
        compare_type=True,
        compare_server_default=True,
    )

    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Create an async engine and run migrations inside a sync bridge."""
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
