"""
AI Agent Service

This service provides the interface between FastAPI endpoints and the
LangGraph orchestrator. It handles session management, tool registration,
and response formatting.

Includes streaming support for real-time response delivery.
"""

import asyncio
import json
import logging
import os
import uuid
from typing import Any, AsyncGenerator, Callable, Dict, List, Optional
from datetime import datetime

from anthropic import Anthropic, AsyncAnthropic
from sqlalchemy.orm import Session

from .orchestrator import run_orchestrator, OrchestratorSession
from .state import create_initial_state, QueryIntent

logger = logging.getLogger(__name__)


class AIAgentService:
    """
    Service class for the LangGraph AI Agent.

    This class provides methods to run the agent from FastAPI endpoints,
    managing the integration with the database session and user context.
    """

    def __init__(
        self,
        db: Session,
        current_user: Any,
        autonomous_mode: bool = True
    ):
        """
        Initialize the AI Agent Service.

        Args:
            db: SQLAlchemy database session
            current_user: Authenticated user object
            autonomous_mode: Whether to auto-execute low-risk actions
        """
        self.db = db
        self.current_user = current_user
        self.autonomous_mode = autonomous_mode

        # Initialize Anthropic clients (sync and async)
        self.anthropic_client = Anthropic(
            api_key=os.getenv("ANTHROPIC_API_KEY")
        )
        self.async_anthropic_client = AsyncAnthropic(
            api_key=os.getenv("ANTHROPIC_API_KEY")
        )

        # Model configuration
        self.model = "claude-sonnet-4-20250514"

        # Tool functions will be registered when processing
        self._tool_functions: Dict[str, Callable] = {}

        # Tool definitions for API calls
        self._tool_definitions: List[Dict] = []

    def register_tool(self, name: str, func: Callable):
        """Register a tool function that the agent can use."""
        self._tool_functions[name] = func

    def register_tools(self, tools: Dict[str, Callable]):
        """Register multiple tool functions."""
        self._tool_functions.update(tools)

    def set_tool_definitions(self, definitions: List[Dict]):
        """Set custom tool definitions for API calls."""
        self._tool_definitions = definitions

    def set_model(self, model: str):
        """Set the model to use for API calls."""
        self.model = model

    async def process_message(
        self,
        message: str,
        conversation_history: Optional[list] = None,
        return_structured: bool = False
    ) -> Dict[str, Any]:
        """
        Process a user message through the LangGraph orchestrator.

        Args:
            message: User's input message
            conversation_history: Previous messages in the conversation
            return_structured: Whether to return structured response data

        Returns:
            Response dictionary with text and metadata
        """
        try:
            # Run the orchestrator
            result = await run_orchestrator(
                message=message,
                user_id=str(self.current_user.id),
                user_email=self.current_user.email,
                user_role=getattr(self.current_user, 'role', 'loan_officer'),
                tool_functions=self._tool_functions,
                anthropic_client=self.anthropic_client,
                autonomous_mode=self.autonomous_mode,
                conversation_history=conversation_history,
                return_structured=return_structured
            )

            # Log the interaction
            await self._log_interaction(message, result)

            return result

        except Exception as e:
            logger.error(f"AI Agent processing failed: {e}", exc_info=True)
            return {
                "response": "I apologize, but I encountered an error. Please try again.",
                "error": str(e)
            }

    async def process_message_stream(
        self,
        message: str,
        conversation_history: Optional[list] = None,
        system_prompt: Optional[str] = None,
        data_context: Optional[str] = None
    ) -> AsyncGenerator[Dict[str, Any], None]:
        """
        Process a user message and stream the response in real-time.

        This reduces perceived latency from ~28s to <2s by yielding tokens
        as they're generated by the model.

        Args:
            message: User's input message
            conversation_history: Previous messages in the conversation
            system_prompt: Optional custom system prompt
            data_context: Optional data context to include

        Yields:
            Response chunks with type and content:
            - {"type": "content", "content": "..."} for text chunks
            - {"type": "tool_use", "tool": "...", "input": {...}} for tool calls
            - {"type": "tool_result", "result": {...}} for tool results
            - {"type": "done", "full_response": "..."} when complete
            - {"type": "error", "error": "..."} on failure
        """
        try:
            # Build messages array
            messages = self._build_messages(message, conversation_history)

            # Build system prompt with context
            full_system_prompt = self._build_system_prompt(system_prompt, data_context)

            # Get tool definitions
            tools = self._get_tool_definitions()

            # Track full response for logging
            full_response = ""

            # Stream response using async client
            async with self.async_anthropic_client.messages.stream(
                model=self.model,
                max_tokens=4000,
                system=full_system_prompt,
                messages=messages,
                tools=tools if tools else None
            ) as stream:
                # Yield text chunks as they arrive
                async for text in stream.text_stream:
                    full_response += text
                    yield {
                        "type": "content",
                        "content": text
                    }

                # Get final message to check for tool calls
                final_message = await stream.get_final_message()

            # Handle tool calls if present
            if final_message.stop_reason == "tool_use":
                # Extract tool use blocks
                tool_uses = [
                    block for block in final_message.content
                    if block.type == "tool_use"
                ]

                for tool_use in tool_uses:
                    # Notify about tool call
                    yield {
                        "type": "tool_use",
                        "tool": tool_use.name,
                        "tool_id": tool_use.id,
                        "input": tool_use.input
                    }

                    # Execute the tool
                    tool_result = await self._execute_tool(
                        tool_use.name,
                        tool_use.input
                    )

                    # Yield tool result
                    yield {
                        "type": "tool_result",
                        "tool": tool_use.name,
                        "result": tool_result
                    }

                # Continue conversation with tool results
                tool_results_content = [
                    {
                        "type": "tool_result",
                        "tool_use_id": tool_use.id,
                        "content": json.dumps(
                            await self._execute_tool(tool_use.name, tool_use.input)
                        )
                    }
                    for tool_use in tool_uses
                ]

                # Add assistant message and tool results to messages
                messages.append({
                    "role": "assistant",
                    "content": final_message.content
                })
                messages.append({
                    "role": "user",
                    "content": tool_results_content
                })

                # Stream final response after tool execution
                async with self.async_anthropic_client.messages.stream(
                    model=self.model,
                    max_tokens=4000,
                    system=full_system_prompt,
                    messages=messages
                ) as final_stream:
                    async for text in final_stream.text_stream:
                        full_response += text
                        yield {
                            "type": "content",
                            "content": text
                        }

            # Final done message
            yield {
                "type": "done",
                "full_response": full_response
            }

            # Log the interaction
            await self._log_interaction(message, {"response": full_response})

        except Exception as e:
            logger.error(f"Streaming error: {e}", exc_info=True)
            yield {
                "type": "error",
                "error": str(e)
            }

    async def chat_streaming(
        self,
        message: str,
        context: Optional[Dict[str, Any]] = None,
        session_id: Optional[str] = None
    ) -> AsyncGenerator[Dict[str, Any], None]:
        """
        Stream AI responses in real-time with full LangGraph pipeline integration.

        This method runs through the complete agent pipeline (analyze -> gather ->
        reason -> execute -> respond) while streaming status updates and results.

        Args:
            message: User's input message
            context: Optional additional context
            session_id: Optional session ID for conversation continuity

        Yields:
            Dict with event and data keys for SSE compatibility:
            - event: status - Progress updates (loading, analyzing, gathering, reasoning, responding)
            - event: tool - Tool execution status
            - event: content - Response text chunks
            - event: complete - Final metadata
            - event: error - Error messages
        """
        # Generate session ID if not provided
        if not session_id:
            session_id = str(uuid.uuid4())

        started_at = datetime.utcnow()

        try:
            # Status: Loading context
            yield {
                "event": "status",
                "data": {
                    "status": "loading",
                    "message": "Loading your context..."
                }
            }

            # Get user context
            user_id = str(self.current_user.id)
            user_email = self.current_user.email
            user_role = getattr(self.current_user, 'role', 'loan_officer')

            # Status: Analyzing
            yield {
                "event": "status",
                "data": {
                    "status": "analyzing",
                    "message": "Analyzing your query..."
                }
            }

            # Create initial state for the pipeline
            initial_state = create_initial_state(
                user_message=message,
                user_id=user_id,
                user_email=user_email,
                user_role=user_role,
                conversation_id=session_id
            )

            # Add context if provided
            if context:
                initial_state["relevant_context"] = context

            # Import node functions
            from .nodes.analyze import analyze_query
            from .nodes.gather import gather_data
            from .nodes.reason import reason_and_analyze
            from .nodes.execute import execute_actions
            from .nodes.respond import generate_response

            # Node 1: Analyze Query
            current_state = await analyze_query(initial_state, self.anthropic_client)
            required_tools = current_state.get("required_tools", [])

            # Node 2: Gather Data
            if required_tools:
                yield {
                    "event": "status",
                    "data": {
                        "status": "gathering",
                        "message": f"Gathering data from {len(required_tools)} sources...",
                        "tools": required_tools
                    }
                }

                # Stream tool calls
                for tool_name in required_tools:
                    yield {
                        "event": "tool",
                        "data": {
                            "tool_name": tool_name,
                            "status": "executing"
                        }
                    }

                current_state = await gather_data(current_state, self._tool_functions)

                # Stream tool results
                tool_calls = current_state.get("tool_calls", [])
                for tool_call in tool_calls:
                    yield {
                        "event": "tool",
                        "data": {
                            "tool_name": tool_call.tool_name,
                            "status": "completed",
                            "success": tool_call.result is not None,
                            "execution_time_ms": tool_call.execution_time_ms or 0
                        }
                    }

            # Node 3: Reason and Analyze
            yield {
                "event": "status",
                "data": {
                    "status": "reasoning",
                    "message": "Analyzing the data..."
                }
            }

            current_state = await reason_and_analyze(current_state, self.anthropic_client)

            # Node 4: Execute Actions (if needed)
            actions_to_execute = current_state.get("actions_pending", [])
            if actions_to_execute and self.autonomous_mode:
                yield {
                    "event": "status",
                    "data": {
                        "status": "executing",
                        "message": f"Executing {len(actions_to_execute)} actions..."
                    }
                }

                current_state = await execute_actions(
                    current_state,
                    self._tool_functions,
                    self.autonomous_mode
                )

                # Report executed actions
                executed = current_state.get("actions_executed", [])
                for action in executed:
                    yield {
                        "event": "action",
                        "data": {
                            "action_type": action.action_type,
                            "success": action.success,
                            "message": action.message
                        }
                    }

            # Node 5: Generate Response
            yield {
                "event": "status",
                "data": {
                    "status": "responding",
                    "message": "Generating response..."
                }
            }

            current_state = await generate_response(current_state, self.anthropic_client)

            # Stream response content
            response_text = current_state.get("response", "")

            if response_text:
                # Stream in chunks for smoother delivery
                chunks = self._split_response_for_streaming(response_text)

                for chunk in chunks:
                    if chunk.strip():
                        yield {
                            "event": "content",
                            "data": {
                                "content": chunk
                            }
                        }
                        # Small delay for readability
                        await asyncio.sleep(0.03)

            # Calculate execution time
            completed_at = datetime.utcnow()
            execution_time_ms = (completed_at - started_at).total_seconds() * 1000

            # Log the interaction
            await self._log_interaction(message, {
                "response": response_text,
                "intent": current_state.get("query_intent", QueryIntent.GENERAL_QUERY).value,
                "confidence": current_state.get("confidence_score", 0.5),
                "processing_time_seconds": execution_time_ms / 1000
            })

            # Stream completion with full metadata
            yield {
                "event": "complete",
                "data": {
                    "session_id": session_id,
                    "full_response": response_text,
                    "tools_used": [tc.tool_name for tc in current_state.get("tool_calls", [])],
                    "insights": current_state.get("key_insights", []),
                    "follow_up_suggestions": current_state.get("follow_up_suggestions", []),
                    "execution_time_ms": execution_time_ms,
                    "query_intent": current_state.get("query_intent", QueryIntent.GENERAL_QUERY).value,
                    "data_quality": current_state.get("data_quality", "unknown")
                }
            }

        except Exception as e:
            logger.error(f"Chat streaming error: {str(e)}", exc_info=True)
            yield {
                "event": "error",
                "data": {
                    "error": str(e),
                    "message": "An error occurred while processing your request."
                }
            }

    def _split_response_for_streaming(self, text: str) -> List[str]:
        """Split response text into chunks for smooth streaming."""
        chunks = []

        # First try to split by paragraphs
        paragraphs = text.split('\n\n')

        for para in paragraphs:
            if len(para) > 200:
                # Split long paragraphs by sentences
                sentences = para.replace('. ', '.|').split('|')
                for sentence in sentences:
                    if sentence.strip():
                        chunks.append(sentence + ' ')
            else:
                chunks.append(para + '\n\n')

        return chunks

    def _build_messages(
        self,
        message: str,
        conversation_history: Optional[list] = None
    ) -> List[Dict[str, Any]]:
        """Build the messages array for the API call."""
        messages = []

        # Add conversation history if provided
        if conversation_history:
            for msg in conversation_history[-10:]:  # Last 10 turns
                role = msg.get("role", "user")
                content = msg.get("content", "")
                if role in ["user", "assistant"] and content:
                    messages.append({"role": role, "content": content})

        # Add current message
        messages.append({"role": "user", "content": message})

        return messages

    def _build_system_prompt(
        self,
        custom_prompt: Optional[str] = None,
        data_context: Optional[str] = None
    ) -> str:
        """Build the system prompt with context."""
        base_prompt = custom_prompt or """You are an expert AI assistant for a mortgage CRM system.
You help loan officers manage their pipeline, track tasks, and make informed decisions.
Be concise, actionable, and always reference specific data when available.
Format responses with markdown for clarity."""

        if data_context:
            return f"{base_prompt}\n\n{data_context}"

        return base_prompt

    def _get_tool_definitions(self) -> List[Dict]:
        """Get tool definitions for the API call."""
        if self._tool_definitions:
            return self._tool_definitions

        # Default tool definitions based on registered functions
        definitions = []

        if "get_pipeline" in self._tool_functions:
            definitions.append({
                "name": "get_pipeline",
                "description": "Get pipeline summary with leads and loans by stage",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "include_details": {
                            "type": "boolean",
                            "description": "Include detailed loan/lead info"
                        }
                    }
                }
            })

        if "get_tasks" in self._tool_functions:
            definitions.append({
                "name": "get_tasks",
                "description": "Get user's tasks with optional time filtering",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "timeframe": {
                            "type": "string",
                            "enum": ["today", "tomorrow", "this_week", "overdue", "all"],
                            "description": "Time filter for tasks"
                        }
                    }
                }
            })

        if "search_leads" in self._tool_functions:
            definitions.append({
                "name": "search_leads",
                "description": "Search for leads by name, email, or phone",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "query": {
                            "type": "string",
                            "description": "Search query"
                        },
                        "limit": {
                            "type": "integer",
                            "description": "Max results",
                            "default": 10
                        }
                    },
                    "required": ["query"]
                }
            })

        if "search_loans" in self._tool_functions:
            definitions.append({
                "name": "search_loans",
                "description": "Search for loans by borrower name, loan number, or property address",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "query": {
                            "type": "string",
                            "description": "Search query"
                        },
                        "limit": {
                            "type": "integer",
                            "description": "Max results",
                            "default": 10
                        }
                    },
                    "required": ["query"]
                }
            })

        if "create_task" in self._tool_functions:
            definitions.append({
                "name": "create_task",
                "description": "Create a new task for the user",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "title": {
                            "type": "string",
                            "description": "Task title"
                        },
                        "description": {
                            "type": "string",
                            "description": "Task description"
                        },
                        "due_date": {
                            "type": "string",
                            "description": "Due date in ISO format"
                        },
                        "priority": {
                            "type": "string",
                            "enum": ["high", "medium", "low"],
                            "description": "Task priority"
                        },
                        "loan_id": {
                            "type": "integer",
                            "description": "Associated loan ID"
                        },
                        "lead_id": {
                            "type": "integer",
                            "description": "Associated lead ID"
                        }
                    },
                    "required": ["title"]
                }
            })

        if "get_pipeline_metrics" in self._tool_functions:
            definitions.append({
                "name": "get_pipeline_metrics",
                "description": "Get pipeline analytics and metrics",
                "input_schema": {
                    "type": "object",
                    "properties": {}
                }
            })

        if "get_rate_lock_advisory" in self._tool_functions:
            definitions.append({
                "name": "get_rate_lock_advisory",
                "description": "Get rate lock advisory based on market conditions",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "days_to_close": {
                            "type": "integer",
                            "description": "Days until closing",
                            "default": 30
                        }
                    }
                }
            })

        if "get_daily_priorities" in self._tool_functions:
            definitions.append({
                "name": "get_daily_priorities",
                "description": "Get prioritized list of actions for today",
                "input_schema": {
                    "type": "object",
                    "properties": {}
                }
            })

        return definitions

    async def _execute_tool(self, tool_name: str, args: Dict) -> Dict[str, Any]:
        """Execute a registered tool and return its result."""
        if tool_name not in self._tool_functions:
            return {"error": f"Unknown tool: {tool_name}"}

        try:
            func = self._tool_functions[tool_name]
            result = await func(args)
            return result
        except Exception as e:
            logger.error(f"Tool execution error ({tool_name}): {e}")
            return {"error": str(e)}

    async def _log_interaction(self, message: str, result: Dict[str, Any]):
        """Log the AI interaction for analytics and debugging."""
        try:
            # Import here to avoid circular imports
            from sqlalchemy import text

            log_query = text("""
                INSERT INTO ai_interactions (
                    user_id, message, response, intent, confidence,
                    processing_time_seconds, created_at
                ) VALUES (
                    :user_id, :message, :response, :intent, :confidence,
                    :processing_time, NOW()
                )
            """)

            self.db.execute(log_query, {
                "user_id": self.current_user.id,
                "message": message[:1000],  # Truncate if too long
                "response": result.get("response", "")[:5000],
                "intent": result.get("intent", "unknown"),
                "confidence": result.get("confidence", 0),
                "processing_time": result.get("processing_time_seconds", 0)
            })
            self.db.commit()

        except Exception as e:
            # Don't fail the request if logging fails
            logger.warning(f"Failed to log AI interaction: {e}")


def create_tool_functions_from_main(db: Session, current_user: Any) -> Dict[str, Callable]:
    """
    Create tool functions that match the existing main.py implementations.

    This function creates async wrappers around the existing tool implementations
    in main.py so they can be used with the LangGraph orchestrator.

    Args:
        db: Database session
        current_user: Current user object

    Returns:
        Dictionary mapping tool names to async functions
    """
    from sqlalchemy import text
    from datetime import datetime, timedelta

    tools = {}

    # ============ Pipeline Tools ============

    async def execute_get_pipeline(args):
        """Get pipeline summary with leads and loans by stage."""
        include_details = args.get("include_details", True)

        try:
            # Get leads using raw SQL to avoid import issues
            lead_rows = db.execute(
                text("""SELECT id, name, email, phone, stage
                       FROM leads WHERE owner_id = :user_id"""),
                {"user_id": current_user.id}
            ).fetchall()

            # Get loans using raw SQL
            loan_rows = db.execute(
                text("""SELECT id, loan_number, borrower_name, stage, amount,
                       processor, underwriter, days_in_stage, closing_date
                       FROM loans WHERE loan_officer_id = :user_id"""),
                {"user_id": current_user.id}
            ).fetchall()

            # Organize leads by stage
            lead_stages = {}
            for lead in lead_rows:
                stage = str(lead.stage) if lead.stage else "New"
                if stage not in lead_stages:
                    lead_stages[stage] = {"count": 0, "items": []}
                lead_stages[stage]["count"] += 1
                if include_details:
                    lead_stages[stage]["items"].append({
                        "id": lead.id,
                        "name": lead.name,
                        "type": "lead"
                    })

            # Organize loans by stage
            loan_stages = {}
            for loan in loan_rows:
                stage = str(loan.stage) if loan.stage else "Unknown"
                if stage not in loan_stages:
                    loan_stages[stage] = {"count": 0, "items": []}
                loan_stages[stage]["count"] += 1
                if include_details:
                    loan_stages[stage]["items"].append({
                        "id": loan.id,
                        "name": loan.borrower_name or f"Loan #{loan.id}",
                        "amount": float(loan.amount) if loan.amount else 0,
                        "processor": loan.processor,
                        "underwriter": loan.underwriter,
                        "days_in_stage": loan.days_in_stage,
                        "closing_date": loan.closing_date.isoformat() if loan.closing_date else None,
                        "type": "loan"
                    })

            return {
                "total_leads": len(lead_rows),
                "total_loans": len(loan_rows),
                "lead_stages": lead_stages,
                "loan_stages": loan_stages,
                "summary": f"{len(lead_rows)} leads, {len(loan_rows)} active loans"
            }
        except Exception as e:
            logger.error(f"Error in get_pipeline: {e}")
            db.rollback()
            return {"error": str(e), "total_leads": 0, "total_loans": 0}

    tools["get_pipeline"] = execute_get_pipeline

    # ============ Task Tools ============

    async def execute_get_tasks(args):
        """Get user's tasks for a specific timeframe."""
        timeframe = args.get("timeframe", "today")
        today = datetime.now().date()

        # Query ai_tasks table (the active task table) instead of tasks
        task_query = text("""
            SELECT t.id, t.title, t.due_date, t.type as status, t.priority, t.description,
                   COALESCE(t.borrower_name, ln.borrower_name, ld.name) as borrower_name,
                   ln.amount as loan_amount, ln.stage as loan_stage, ln.loan_number,
                   t.loan_id, t.lead_id
            FROM ai_tasks t
            LEFT JOIN loans ln ON t.loan_id = ln.id
            LEFT JOIN leads ld ON t.lead_id = ld.id
            WHERE t.assigned_to_id = :user_id AND t.type != 'Completed'
            ORDER BY
                CASE WHEN t.priority = 'high' THEN 1 WHEN t.priority = 'medium' THEN 2 ELSE 3 END,
                t.due_date ASC NULLS LAST
        """)

        result = db.execute(task_query, {"user_id": current_user.id})
        all_tasks = result.fetchall()

        filtered_tasks = []
        for row in all_tasks:
            task_date = row[2].date() if row[2] else None
            include = False

            if timeframe == "today":
                include = task_date == today
            elif timeframe == "tomorrow":
                include = task_date == today + timedelta(days=1)
            elif timeframe == "this_week":
                include = task_date and today <= task_date <= today + timedelta(days=7)
            elif timeframe == "overdue":
                include = task_date and task_date < today
            else:
                include = True

            if include:
                filtered_tasks.append(row)

        return {
            "count": len(filtered_tasks),
            "timeframe": timeframe,
            "tasks": [{
                "id": r[0],
                "title": r[1],
                "due_date": r[2].isoformat() if r[2] else None,
                "status": r[3],
                "priority": r[4],
                "description": r[5][:100] if r[5] else None,
                "borrower_name": r[6],
                "loan_amount": float(r[7]) if r[7] else None,
                "loan_stage": r[8],
                "loan_number": r[9]
            } for r in filtered_tasks[:15]]
        }

    tools["get_tasks"] = execute_get_tasks

    # ============ Search Tools ============

    async def execute_search_leads(args):
        """Search for leads by name, email, or phone."""
        query_str = args.get("query", "")
        limit = args.get("limit", 10)

        try:
            if query_str:
                search = f"%{query_str}%"
                lead_rows = db.execute(
                    text("""SELECT id, name, email, phone, stage
                           FROM leads
                           WHERE owner_id = :user_id
                           AND (name ILIKE :search OR email ILIKE :search OR phone ILIKE :search)
                           LIMIT :limit"""),
                    {"user_id": current_user.id, "search": search, "limit": limit}
                ).fetchall()
            else:
                lead_rows = db.execute(
                    text("""SELECT id, name, email, phone, stage
                           FROM leads WHERE owner_id = :user_id LIMIT :limit"""),
                    {"user_id": current_user.id, "limit": limit}
                ).fetchall()

            return {
                "count": len(lead_rows),
                "leads": [{
                    "id": l.id,
                    "name": l.name,
                    "email": l.email,
                    "phone": l.phone,
                    "stage": str(l.stage) if l.stage else None
                } for l in lead_rows]
            }
        except Exception as e:
            logger.error(f"Error in search_leads: {e}")
            db.rollback()
            return {"count": 0, "leads": [], "error": str(e)}

    tools["search_leads"] = execute_search_leads

    # ============ Loan Search Tools ============

    async def execute_search_loans(args):
        """Search for loans by borrower name, loan number, or property address."""
        query_str = args.get("query", "")
        limit = args.get("limit", 10)

        try:
            if query_str:
                search = f"%{query_str}%"
                loan_rows = db.execute(
                    text("""SELECT id, loan_number, borrower_name, stage, amount,
                           processor, underwriter, property_address, closing_date
                           FROM loans
                           WHERE loan_officer_id = :user_id
                           AND (borrower_name ILIKE :search OR loan_number ILIKE :search
                                OR property_address ILIKE :search)
                           LIMIT :limit"""),
                    {"user_id": current_user.id, "search": search, "limit": limit}
                ).fetchall()
            else:
                loan_rows = db.execute(
                    text("""SELECT id, loan_number, borrower_name, stage, amount,
                           processor, underwriter, property_address, closing_date
                           FROM loans WHERE loan_officer_id = :user_id LIMIT :limit"""),
                    {"user_id": current_user.id, "limit": limit}
                ).fetchall()

            return {
                "count": len(loan_rows),
                "loans": [{
                    "id": l.id,
                    "loan_number": l.loan_number,
                    "borrower_name": l.borrower_name,
                    "stage": str(l.stage) if l.stage else None,
                    "amount": float(l.amount) if l.amount else None,
                    "processor": l.processor,
                    "underwriter": l.underwriter,
                    "property_address": l.property_address,
                    "closing_date": l.closing_date.isoformat() if l.closing_date else None
                } for l in loan_rows]
            }
        except Exception as e:
            logger.error(f"Error in search_loans: {e}")
            db.rollback()
            return {"count": 0, "loans": [], "error": str(e)}

    tools["search_loans"] = execute_search_loans

    # ============ Task Creation Tools ============

    async def execute_create_task(args):
        """Create a new task for the user."""
        title = args.get("title", "New Task")
        description = args.get("description", "")
        due_date = args.get("due_date")
        priority = args.get("priority", "medium")
        loan_id = args.get("loan_id")
        lead_id = args.get("lead_id")

        try:
            # Parse due_date if provided
            due_datetime = None
            if due_date:
                try:
                    due_datetime = datetime.fromisoformat(due_date.replace('Z', '+00:00'))
                except:
                    due_datetime = datetime.now() + timedelta(days=1)

            # Insert into ai_tasks table (the active task table)
            result = db.execute(
                text("""INSERT INTO ai_tasks (title, description, due_date, priority, type,
                       assigned_to_id, loan_id, lead_id, created_at, updated_at)
                       VALUES (:title, :description, :due_date, :priority, 'In Progress',
                       :assigned_to_id, :loan_id, :lead_id, NOW(), NOW())
                       RETURNING id, title"""),
                {
                    "title": title,
                    "description": description,
                    "due_date": due_datetime,
                    "priority": priority,
                    "assigned_to_id": current_user.id,
                    "loan_id": loan_id,
                    "lead_id": lead_id
                }
            )
            db.commit()
            row = result.fetchone()

            # Invalidate task-related caches for this user
            try:
                from core.cache import invalidate_user_cache
                await invalidate_user_cache(str(current_user.id))
            except Exception as cache_e:
                logger.debug(f"Cache invalidation skipped: {cache_e}")

            return {
                "success": True,
                "task_id": row.id,
                "title": row.title,
                "message": f"Task '{title}' created successfully"
            }
        except Exception as e:
            logger.error(f"Error in create_task: {e}")
            db.rollback()
            return {"success": False, "error": str(e)}

    tools["create_task"] = execute_create_task

    # ============ Analytics Tools ============

    async def execute_get_pipeline_metrics(args):
        """Get pipeline analytics and metrics."""
        try:
            # Get loan counts by stage
            stage_counts = db.execute(
                text("""SELECT stage, COUNT(*) as count, SUM(amount) as total_amount
                       FROM loans WHERE loan_officer_id = :user_id
                       GROUP BY stage"""),
                {"user_id": current_user.id}
            ).fetchall()

            # Get closing metrics
            closing_metrics = db.execute(
                text("""SELECT
                       COUNT(*) FILTER (WHERE closing_date <= CURRENT_DATE + INTERVAL '7 days') as closing_7_days,
                       COUNT(*) FILTER (WHERE closing_date <= CURRENT_DATE + INTERVAL '30 days') as closing_30_days,
                       SUM(amount) FILTER (WHERE closing_date <= CURRENT_DATE + INTERVAL '30 days') as volume_30_days
                       FROM loans WHERE loan_officer_id = :user_id AND stage != 'closed'"""),
                {"user_id": current_user.id}
            ).fetchone()

            return {
                "stage_breakdown": [{
                    "stage": str(s.stage) if s.stage else "Unknown",
                    "count": s.count,
                    "total_amount": float(s.total_amount) if s.total_amount else 0
                } for s in stage_counts],
                "closing_7_days": closing_metrics.closing_7_days or 0,
                "closing_30_days": closing_metrics.closing_30_days or 0,
                "volume_30_days": float(closing_metrics.volume_30_days) if closing_metrics.volume_30_days else 0
            }
        except Exception as e:
            logger.error(f"Error in get_pipeline_metrics: {e}")
            db.rollback()
            return {"error": str(e)}

    tools["get_pipeline_metrics"] = execute_get_pipeline_metrics

    # ============ Rate Lock Advisory Tools ============

    async def execute_get_rate_lock_advisory(args):
        """Get rate lock advisory based on market conditions and loan specifics."""
        days_to_close = args.get("days_to_close", 30)

        try:
            # Get loans closing in the specified timeframe (use uppercase for LoanStage enum)
            loans = db.execute(
                text("""SELECT id, loan_number, borrower_name, amount, closing_date,
                       rate, lock_expiration_date
                       FROM loans
                       WHERE loan_officer_id = :user_id
                       AND closing_date <= CURRENT_DATE + INTERVAL ':days days'
                       AND stage::text NOT IN ('CLOSED', 'DENIED', 'WITHDRAWN')
                       ORDER BY closing_date ASC""".replace(':days', str(days_to_close))),
                {"user_id": current_user.id}
            ).fetchall()

            # Provide advisory based on general market principles
            advisory = {
                "recommendation": "float" if days_to_close > 45 else "lock",
                "confidence": 0.7,
                "reasoning": "Based on typical market volatility and time to close",
                "loans_affected": len(loans),
                "loans": [{
                    "loan_number": l.loan_number,
                    "borrower_name": l.borrower_name,
                    "amount": float(l.amount) if l.amount else 0,
                    "closing_date": l.closing_date.isoformat() if l.closing_date else None,
                    "current_rate": float(l.rate) if l.rate else None,
                    "lock_status": "locked" if l.lock_expiration_date else "floating"
                } for l in loans[:10]]
            }

            return advisory
        except Exception as e:
            logger.error(f"Error in get_rate_lock_advisory: {e}")
            db.rollback()
            return {"error": str(e), "recommendation": "consult_manager"}

    tools["get_rate_lock_advisory"] = execute_get_rate_lock_advisory

    # ============ Daily Priorities Tools ============

    async def execute_get_daily_priorities(args):
        """Get prioritized list of actions for today."""
        try:
            # Get overdue tasks from ai_tasks table (the active task table)
            overdue_tasks = db.execute(
                text("""SELECT t.id, t.title, t.due_date, t.priority,
                       COALESCE(t.borrower_name, ln.borrower_name, ld.name) as contact_name
                       FROM ai_tasks t
                       LEFT JOIN loans ln ON t.loan_id = ln.id
                       LEFT JOIN leads ld ON t.lead_id = ld.id
                       WHERE t.assigned_to_id = :user_id
                       AND t.type != 'Completed'
                       AND t.due_date < CURRENT_DATE
                       ORDER BY
                           CASE WHEN t.priority = 'high' THEN 1
                                WHEN t.priority = 'medium' THEN 2
                                ELSE 3 END,
                           t.due_date ASC
                       LIMIT 5"""),
                {"user_id": current_user.id}
            ).fetchall()

            # Get today's tasks
            today_tasks = db.execute(
                text("""SELECT t.id, t.title, t.due_date, t.priority,
                       COALESCE(t.borrower_name, ln.borrower_name, ld.name) as contact_name
                       FROM ai_tasks t
                       LEFT JOIN loans ln ON t.loan_id = ln.id
                       LEFT JOIN leads ld ON t.lead_id = ld.id
                       WHERE t.assigned_to_id = :user_id
                       AND t.type != 'Completed'
                       AND t.due_date::date = CURRENT_DATE
                       ORDER BY
                           CASE WHEN t.priority = 'high' THEN 1
                                WHEN t.priority = 'medium' THEN 2
                                ELSE 3 END
                       LIMIT 10"""),
                {"user_id": current_user.id}
            ).fetchall()

            # Also get tomorrow's tasks
            tomorrow_tasks = db.execute(
                text("""SELECT t.id, t.title, t.due_date, t.priority,
                       COALESCE(t.borrower_name, ln.borrower_name, ld.name) as contact_name
                       FROM ai_tasks t
                       LEFT JOIN loans ln ON t.loan_id = ln.id
                       LEFT JOIN leads ld ON t.lead_id = ld.id
                       WHERE t.assigned_to_id = :user_id
                       AND t.type != 'Completed'
                       AND t.due_date::date = CURRENT_DATE + INTERVAL '1 day'
                       ORDER BY
                           CASE WHEN t.priority = 'high' THEN 1
                                WHEN t.priority = 'medium' THEN 2
                                ELSE 3 END
                       LIMIT 5"""),
                {"user_id": current_user.id}
            ).fetchall()

            # Get loans closing soon (use uppercase for LoanStage enum values)
            closing_soon = db.execute(
                text("""SELECT id, loan_number, borrower_name, closing_date, stage, amount
                       FROM loans
                       WHERE loan_officer_id = :user_id
                       AND closing_date <= CURRENT_DATE + INTERVAL '7 days'
                       AND stage::text NOT IN ('CLOSED', 'DENIED', 'WITHDRAWN')
                       ORDER BY closing_date ASC
                       LIMIT 5"""),
                {"user_id": current_user.id}
            ).fetchall()

            return {
                "overdue_tasks": [{
                    "id": t.id,
                    "title": t.title,
                    "due_date": t.due_date.isoformat() if t.due_date else None,
                    "priority": t.priority,
                    "contact_name": t.contact_name
                } for t in overdue_tasks],
                "today_tasks": [{
                    "id": t.id,
                    "title": t.title,
                    "due_date": t.due_date.isoformat() if t.due_date else None,
                    "priority": t.priority,
                    "contact_name": t.contact_name
                } for t in today_tasks],
                "tomorrow_tasks": [{
                    "id": t.id,
                    "title": t.title,
                    "due_date": t.due_date.isoformat() if t.due_date else None,
                    "priority": t.priority,
                    "contact_name": t.contact_name
                } for t in tomorrow_tasks],
                "closing_soon": [{
                    "loan_number": l.loan_number,
                    "borrower_name": l.borrower_name,
                    "closing_date": l.closing_date.isoformat() if l.closing_date else None,
                    "stage": str(l.stage) if l.stage else None,
                    "amount": float(l.amount) if l.amount else 0
                } for l in closing_soon],
                "summary": f"{len(overdue_tasks)} overdue, {len(today_tasks)} due today, {len(tomorrow_tasks)} due tomorrow, {len(closing_soon)} closing within 7 days"
            }
        except Exception as e:
            logger.error(f"Error in get_daily_priorities: {e}")
            db.rollback()  # Roll back to allow subsequent queries
            return {"error": str(e)}

    tools["get_daily_priorities"] = execute_get_daily_priorities

    return tools


async def create_ai_agent_service(
    db: Session,
    current_user: Any,
    autonomous_mode: bool = True
) -> AIAgentService:
    """
    Factory function to create a fully configured AI Agent Service.

    This creates the service and registers all available tools.

    Args:
        db: Database session
        current_user: Current user
        autonomous_mode: Whether to auto-execute actions

    Returns:
        Configured AIAgentService instance
    """
    service = AIAgentService(db, current_user, autonomous_mode)

    # Register tools
    tool_functions = create_tool_functions_from_main(db, current_user)
    service.register_tools(tool_functions)

    return service
