"""
Smart Calendar Constants
========================
Central source of truth for all scheduler durations, limits, and defaults.
"""

# Duration defaults (minutes)
DEFAULT_APPOINTMENT_DURATION_MINUTES = 30
MIN_APPOINTMENT_DURATION_MINUTES = 5
MAX_APPOINTMENT_DURATION_MINUTES = 480
ALLOWED_APPOINTMENT_DURATIONS = [15, 30, 45, 60]

# Buffer times (minutes)
DEFAULT_BUFFER_BEFORE_MINUTES = 5
DEFAULT_BUFFER_AFTER_MINUTES = 5

# Timing windows
DEFAULT_MIN_NOTICE_HOURS = 2
DEFAULT_MAX_ADVANCE_DAYS = 60
SLOT_GENERATION_MAX_DAYS = 45

# Notification windows (hours)
NOTIFICATION_LOOKBACK_HOURS = 72
APPOINTMENT_REMINDER_WINDOW_MINUTES = 60
NOTIFICATION_RECENCY_HOURS = 24

# Rate limits
PUBLIC_BOOKING_RATE_LIMIT = 10
PUBLIC_SLOTS_RATE_LIMIT = 20
BOOKING_RATE_LIMIT_PER_EMAIL = 5
BOOKING_RATE_LIMIT_PER_IP = 5
DEMO_CREATE_RATE_LIMIT = 3

# Pagination
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100
NOTIFICATION_FETCH_LIMIT = 50
MAX_BULK_OPERATION_SIZE = 50

# Reminder limits
MAX_REMINDERS_PER_APPOINTMENT = 10

# Hold TTL
DEFAULT_HOLD_TTL_SECONDS = 300  # 5 minutes
