"""
Power Play Workflow Engine - 7 Workflows per PRD
TL Development, LLC

Implements the 7 Power Play Workflows:
1. Prospect Power Play - Active buyers with 10-month timeline
2. PreQual Power Play - Soft-pulled, financially ready
3. Pre-Approved Power Play - Under contract with tight timelines
4. Long-Term Nurture Power Play - 10+ month buyers (passive)
5. Under Contract Power Play - Active loan management
6. Consumer Referral Power Play - Past clients with referral potential
7. Circle of Cash Flow Power Play - Realtor/professional referral management
"""

from datetime import datetime, timedelta, timezone
from typing import List, Dict, Optional, Any, Tuple
from dataclasses import dataclass, field
from enum import Enum
from sqlalchemy.orm import Session
from sqlalchemy import text
import json
import logging

logger = logging.getLogger(__name__)


# ==============================================================================
# POWER PLAY WORKFLOW TYPES
# ==============================================================================

class PowerPlayType(str, Enum):
    PROSPECT = "prospect_power_play"
    PREQUAL = "prequal_power_play"
    PRE_APPROVED = "pre_approved_power_play"
    LONG_TERM_NURTURE = "long_term_nurture_power_play"
    UNDER_CONTRACT = "under_contract_power_play"
    CONSUMER_REFERRAL = "consumer_referral_power_play"
    CIRCLE_OF_CASH_FLOW = "circle_of_cash_flow_power_play"


class WorkflowActionType(str, Enum):
    TASK = "task"
    EMAIL = "email"
    SMS = "sms"
    ALERT = "alert"
    TAG = "tag"
    DRIP_CAMPAIGN = "drip_campaign"
    STAGE_CHANGE = "stage_change"
    SCHEDULE_TOUCH = "schedule_touch"
    RATE_LOCK_CHECK = "rate_lock_check"


# ==============================================================================
# DATA MODELS
# ==============================================================================

@dataclass
class TouchFrequency:
    """Touch frequency based on buying timeline"""
    platinum: int = 7    # < 3 months, every 7 days
    gold: int = 14       # 4-6 months, every 14 days
    silver: int = 21     # 7-9 months, every 21 days
    green: int = 30      # 10+ months, monthly


@dataclass
class PowerPlayAction:
    """Action generated by a Power Play workflow"""
    action_type: WorkflowActionType
    target: str  # lead, loan_officer, referral_source
    data: Dict[str, Any]
    priority: str = "normal"  # low, normal, high, urgent
    scheduled_for: Optional[datetime] = None
    template: Optional[str] = None


@dataclass
class PowerPlayResult:
    """Result of processing a Power Play workflow"""
    workflow_type: PowerPlayType
    entity_id: int
    entity_type: str  # lead, loan, contact
    actions: List[PowerPlayAction] = field(default_factory=list)
    next_touch_date: Optional[datetime] = None
    status: str = "processed"
    message: str = ""


# ==============================================================================
# POWER PLAY WORKFLOW ENGINE
# ==============================================================================

class PowerPlayEngine:
    """Main engine for processing all 7 Power Play workflows"""

    def __init__(self, db: Session):
        self.db = db
        self.touch_frequency = TouchFrequency()

    # ==========================================================================
    # MAIN ENTRY POINTS
    # ==========================================================================

    def process_lead_workflow(self, lead: Any, trigger: str = None) -> PowerPlayResult:
        """
        Determine and execute appropriate Power Play for a lead.

        Triggers:
        - stage_change: Lead stage changed
        - timeline_update: Buying timeline updated
        - new_lead: New lead created
        - scheduled_touch: Time-based touch due
        """
        # Determine which Power Play applies based on lead stage/timeline
        workflow_type = self._determine_lead_workflow(lead)

        if workflow_type == PowerPlayType.PROSPECT:
            return self._execute_prospect_power_play(lead, trigger)
        elif workflow_type == PowerPlayType.PREQUAL:
            return self._execute_prequal_power_play(lead, trigger)
        elif workflow_type == PowerPlayType.PRE_APPROVED:
            return self._execute_pre_approved_power_play(lead, trigger)
        elif workflow_type == PowerPlayType.LONG_TERM_NURTURE:
            return self._execute_long_term_nurture_power_play(lead, trigger)
        else:
            return PowerPlayResult(
                workflow_type=PowerPlayType.PROSPECT,
                entity_id=lead.id,
                entity_type="lead",
                status="no_workflow",
                message="No applicable Power Play for current lead stage"
            )

    def process_loan_workflow(self, loan: Any, trigger: str = None) -> PowerPlayResult:
        """Execute Under Contract Power Play for active loans"""
        return self._execute_under_contract_power_play(loan, trigger)

    def process_referral_workflow(self, entity: Any, entity_type: str, trigger: str = None) -> PowerPlayResult:
        """Execute referral-related Power Plays"""
        if entity_type == "past_client":
            return self._execute_consumer_referral_power_play(entity, trigger)
        elif entity_type == "referral_partner":
            return self._execute_circle_of_cash_flow_power_play(entity, trigger)
        else:
            return PowerPlayResult(
                workflow_type=PowerPlayType.CONSUMER_REFERRAL,
                entity_id=entity.id,
                entity_type=entity_type,
                status="invalid_type",
                message=f"Unknown entity type: {entity_type}"
            )

    # ==========================================================================
    # WORKFLOW TYPE DETERMINATION
    # ==========================================================================

    def _determine_lead_workflow(self, lead: Any) -> Optional[PowerPlayType]:
        """Determine which Power Play applies based on lead characteristics"""
        stage = str(lead.stage.value) if hasattr(lead.stage, 'value') else str(lead.stage)
        timeline = getattr(lead, 'buying_timeline_category', None)

        # Check stage first
        if stage in ["Pre-Approved", "PreApproved"]:
            return PowerPlayType.PRE_APPROVED

        # Check timeline category
        if timeline:
            timeline_val = timeline.value if hasattr(timeline, 'value') else str(timeline)
            if timeline_val == "Green":  # 10+ months
                return PowerPlayType.LONG_TERM_NURTURE

        # PreQual check - has soft credit pull but not pre-approved
        if stage in ["Application Complete", "Application Started"]:
            return PowerPlayType.PREQUAL

        # Default to Prospect for active buyers
        if stage in ["New", "Attempted Contact", "Prospect"]:
            return PowerPlayType.PROSPECT

        return None

    # ==========================================================================
    # 1. PROSPECT POWER PLAY
    # ==========================================================================

    def _execute_prospect_power_play(self, lead: Any, trigger: str) -> PowerPlayResult:
        """
        Prospect Power Play - Active buyers with 10-month timeline

        Timeline-Based Touch Frequency:
        - Platinum (< 3 mo): Every 7 days
        - Gold (4-6 mo): Every 14 days
        - Silver (7-9 mo): Every 21 days
        - Green (10+ mo): Route to Long-Term Nurture
        """
        actions = []
        first_name = lead.name.split()[0] if lead.name else "there"

        # Determine touch frequency based on timeline
        timeline = getattr(lead, 'buying_timeline_category', None)
        timeline_val = timeline.value if timeline and hasattr(timeline, 'value') else "Silver"

        touch_days = {
            "Platinum": self.touch_frequency.platinum,
            "Gold": self.touch_frequency.gold,
            "Silver": self.touch_frequency.silver,
            "Green": self.touch_frequency.green
        }.get(timeline_val, 14)

        # Route to Long-Term Nurture if Green
        if timeline_val == "Green":
            return self._execute_long_term_nurture_power_play(lead, trigger)

        # Schedule next touch
        next_touch = datetime.now(timezone.utc) + timedelta(days=touch_days)

        if trigger == "new_lead":
            # New prospect actions
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.TASK,
                target="loan_officer",
                data={
                    "title": f"Initial Discovery Call with {first_name}",
                    "description": "Complete needs analysis: timeline, budget, loan type preference, concerns",
                    "due_hours": 24,
                    "priority": "high",
                    "lead_id": lead.id
                },
                priority="high"
            ))

            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.TAG,
                target="lead",
                data={
                    "lead_id": lead.id,
                    "tags": [f"timeline:{timeline_val.lower()}", "prospect_power_play"]
                }
            ))

            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.DRIP_CAMPAIGN,
                target="lead",
                data={
                    "lead_id": lead.id,
                    "campaign": f"prospect_nurture_{timeline_val.lower()}",
                    "start_immediately": True
                }
            ))

        elif trigger == "scheduled_touch":
            # Scheduled touch-point
            touch_type = self._get_varied_touch_type(lead)

            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.TASK,
                target="loan_officer",
                data={
                    "title": f"{touch_type} touch with {first_name}",
                    "description": f"Scheduled {timeline_val} timeline touch. Check for timeline changes, address concerns.",
                    "due_hours": touch_days * 24,
                    "priority": "medium",
                    "lead_id": lead.id
                }
            ))

        elif trigger == "timeline_update":
            # Timeline changed - adjust workflow
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.ALERT,
                target="loan_officer",
                data={
                    "message": f"Timeline updated for {first_name}: now {timeline_val}",
                    "lead_id": lead.id
                }
            ))

            # Update drip campaign
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.DRIP_CAMPAIGN,
                target="lead",
                data={
                    "lead_id": lead.id,
                    "campaign": f"prospect_nurture_{timeline_val.lower()}",
                    "stop_previous": True
                }
            ))

        return PowerPlayResult(
            workflow_type=PowerPlayType.PROSPECT,
            entity_id=lead.id,
            entity_type="lead",
            actions=actions,
            next_touch_date=next_touch,
            status="processed",
            message=f"Prospect Power Play: {len(actions)} actions, next touch in {touch_days} days"
        )

    # ==========================================================================
    # 2. PREQUAL POWER PLAY
    # ==========================================================================

    def _execute_prequal_power_play(self, lead: Any, trigger: str) -> PowerPlayResult:
        """
        PreQual Power Play - Soft-pulled, financially ready

        Focus: Document collection, rate education, timeline management
        """
        actions = []
        first_name = lead.name.split()[0] if lead.name else "there"

        if trigger == "stage_change":
            # Just became PreQual
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.EMAIL,
                target="lead",
                data={
                    "to": lead.email,
                    "subject": f"{first_name}, Your Pre-Qualification is Ready!",
                    "template": "prequal_ready",
                    "lead_name": lead.name
                },
                priority="high"
            ))

            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.TASK,
                target="loan_officer",
                data={
                    "title": f"Document collection call with {first_name}",
                    "description": "Review pre-qual, explain document requirements, set expectations for pre-approval timeline",
                    "due_hours": 24,
                    "priority": "high",
                    "lead_id": lead.id
                },
                priority="high"
            ))

            # Send document checklist
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.EMAIL,
                target="lead",
                data={
                    "to": lead.email,
                    "subject": "Your Document Checklist - Next Steps",
                    "template": "document_checklist",
                    "lead_name": lead.name
                },
                priority="normal",
                scheduled_for=datetime.now(timezone.utc) + timedelta(hours=2)
            ))

        elif trigger == "document_received":
            # Document uploaded - progress tracker
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.ALERT,
                target="loan_officer",
                data={
                    "message": f"Document received from {first_name} - review for completeness",
                    "lead_id": lead.id
                }
            ))

        # Start PreQual nurture campaign
        actions.append(PowerPlayAction(
            action_type=WorkflowActionType.DRIP_CAMPAIGN,
            target="lead",
            data={
                "lead_id": lead.id,
                "campaign": "prequal_to_preapproval",
                "content": ["rate_education", "document_tips", "timeline_updates"]
            }
        ))

        return PowerPlayResult(
            workflow_type=PowerPlayType.PREQUAL,
            entity_id=lead.id,
            entity_type="lead",
            actions=actions,
            next_touch_date=datetime.now(timezone.utc) + timedelta(days=3),
            status="processed",
            message=f"PreQual Power Play: {len(actions)} actions"
        )

    # ==========================================================================
    # 3. PRE-APPROVED POWER PLAY
    # ==========================================================================

    def _execute_pre_approved_power_play(self, lead: Any, trigger: str) -> PowerPlayResult:
        """
        Pre-Approved Power Play - Under contract with tight timelines

        Integration with Rate Lock Intelligence for lock decisions
        """
        actions = []
        first_name = lead.name.split()[0] if lead.name else "there"

        if trigger == "stage_change":
            # Just got pre-approved
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.EMAIL,
                target="lead",
                data={
                    "to": lead.email,
                    "subject": f"Congratulations {first_name}! You're Pre-Approved!",
                    "template": "pre_approval_celebration",
                    "lead_name": lead.name
                },
                priority="urgent"
            ))

            if lead.phone:
                actions.append(PowerPlayAction(
                    action_type=WorkflowActionType.SMS,
                    target="lead",
                    data={
                        "to": lead.phone,
                        "message": f"CONGRATS {first_name}! You're PRE-APPROVED! Check your email for your letter. Time to find your home!"
                    },
                    priority="urgent"
                ))

            # Create realtor connection task
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.TASK,
                target="loan_officer",
                data={
                    "title": f"Connect {first_name} with realtor",
                    "description": "Send pre-approval letter, offer realtor referral if needed, discuss house hunting strategy",
                    "due_hours": 4,
                    "priority": "high",
                    "lead_id": lead.id
                },
                priority="high"
            ))

            # Tag for pre-approved tracking
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.TAG,
                target="lead",
                data={
                    "lead_id": lead.id,
                    "tags": ["pre-approved", "house-hunting", "active"]
                }
            ))

        elif trigger == "under_contract":
            # They found a house!
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.ALERT,
                target="loan_officer",
                data={
                    "message": f"EXCITING! {first_name} is under contract! Initiate loan processing.",
                    "lead_id": lead.id,
                    "priority": "urgent"
                },
                priority="urgent"
            ))

            # Trigger Rate Lock check
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.RATE_LOCK_CHECK,
                target="loan",
                data={
                    "lead_id": lead.id,
                    "trigger": "under_contract",
                    "urgency": "high"
                }
            ))

            # Change stage to Under Contract
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.STAGE_CHANGE,
                target="lead",
                data={
                    "lead_id": lead.id,
                    "new_stage": "Under Contract"
                }
            ))

        # Pre-approval nurture campaign
        actions.append(PowerPlayAction(
            action_type=WorkflowActionType.DRIP_CAMPAIGN,
            target="lead",
            data={
                "lead_id": lead.id,
                "campaign": "pre_approved_house_hunting",
                "content": ["market_updates", "rate_alerts", "house_hunting_tips"]
            }
        ))

        return PowerPlayResult(
            workflow_type=PowerPlayType.PRE_APPROVED,
            entity_id=lead.id,
            entity_type="lead",
            actions=actions,
            next_touch_date=datetime.now(timezone.utc) + timedelta(days=7),
            status="processed",
            message=f"Pre-Approved Power Play: {len(actions)} actions"
        )

    # ==========================================================================
    # 4. LONG-TERM NURTURE POWER PLAY
    # ==========================================================================

    def _execute_long_term_nurture_power_play(self, lead: Any, trigger: str) -> PowerPlayResult:
        """
        Long-Term Nurture Power Play - 10+ month buyers (passive)

        Monthly touches, market education focus
        """
        actions = []
        first_name = lead.name.split()[0] if lead.name else "there"

        # Monthly touch frequency
        next_touch = datetime.now(timezone.utc) + timedelta(days=30)

        if trigger in ["new_lead", "timeline_update"]:
            # Set up long-term nurture
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.TAG,
                target="lead",
                data={
                    "lead_id": lead.id,
                    "tags": ["long-term-nurture", "10-plus-months", "passive"]
                }
            ))

            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.DRIP_CAMPAIGN,
                target="lead",
                data={
                    "lead_id": lead.id,
                    "campaign": "long_term_nurture",
                    "frequency": "monthly",
                    "content": ["market_education", "rate_trends", "homebuyer_tips"]
                }
            ))

            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.EMAIL,
                target="lead",
                data={
                    "to": lead.email,
                    "subject": f"{first_name}, Let's Stay Connected on Your Home Journey",
                    "template": "long_term_welcome",
                    "lead_name": lead.name
                }
            ))

        elif trigger == "scheduled_touch":
            # Monthly educational touch
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.EMAIL,
                target="lead",
                data={
                    "to": lead.email,
                    "subject": "Your Monthly Market Update",
                    "template": "market_update_monthly",
                    "lead_name": lead.name
                }
            ))

        elif trigger == "timeline_shortened":
            # They're ready sooner! Escalate to active workflow
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.ALERT,
                target="loan_officer",
                data={
                    "message": f"HOT: {first_name}'s timeline has shortened! Moving to active prospect.",
                    "lead_id": lead.id,
                    "priority": "high"
                },
                priority="high"
            ))

            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.DRIP_CAMPAIGN,
                target="lead",
                data={
                    "lead_id": lead.id,
                    "campaign": "prospect_nurture_active",
                    "stop_campaign": "long_term_nurture"
                }
            ))

        # Schedule timeline re-check task
        actions.append(PowerPlayAction(
            action_type=WorkflowActionType.SCHEDULE_TOUCH,
            target="lead",
            data={
                "lead_id": lead.id,
                "touch_type": "timeline_check",
                "days_out": 30,
                "auto_reschedule": True
            }
        ))

        return PowerPlayResult(
            workflow_type=PowerPlayType.LONG_TERM_NURTURE,
            entity_id=lead.id,
            entity_type="lead",
            actions=actions,
            next_touch_date=next_touch,
            status="processed",
            message=f"Long-Term Nurture Power Play: {len(actions)} actions, monthly touches"
        )

    # ==========================================================================
    # 5. UNDER CONTRACT POWER PLAY
    # ==========================================================================

    def _execute_under_contract_power_play(self, loan: Any, trigger: str) -> PowerPlayResult:
        """
        Under Contract Power Play - Active loan management

        Rate Lock Intelligence integration, milestone management
        """
        actions = []
        borrower_name = (loan.borrower_name or "Borrower").strip() or "Borrower"
        first_name = borrower_name.split()[0]

        if trigger == "new_contract":
            # New under-contract loan
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.TASK,
                target="loan_officer",
                data={
                    "title": f"Lock decision for {first_name}",
                    "description": "Review Rate Lock Intelligence recommendation. Discuss lock strategy with borrower.",
                    "due_hours": 4,
                    "priority": "urgent",
                    "loan_id": loan.id
                },
                priority="urgent"
            ))

            # Initial Rate Lock check
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.RATE_LOCK_CHECK,
                target="loan",
                data={
                    "loan_id": loan.id,
                    "trigger": "under_contract",
                    "analyze_immediately": True
                }
            ))

            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.EMAIL,
                target="borrower",
                data={
                    "to": getattr(loan, 'borrower_email', None),
                    "subject": f"Your Loan is In Progress, {first_name}!",
                    "template": "loan_in_progress",
                    "borrower_name": borrower_name,
                    "loan_number": loan.loan_number
                }
            ))

        elif trigger == "milestone_reached":
            # Milestone automation
            stage = str(loan.stage.value) if hasattr(loan.stage, 'value') else str(loan.stage)

            milestone_tasks = self._get_milestone_tasks(loan, stage)
            actions.extend(milestone_tasks)

            # Notify borrower of milestone
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.EMAIL,
                target="borrower",
                data={
                    "to": getattr(loan, 'borrower_email', None),
                    "subject": f"Great News! Your Loan Reached {stage}",
                    "template": f"milestone_{stage.lower().replace(' ', '_')}",
                    "borrower_name": borrower_name
                }
            ))

        elif trigger == "rate_lock_expiring":
            # Rate lock expiration warning
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.ALERT,
                target="loan_officer",
                data={
                    "message": f"URGENT: Rate lock expiring for {first_name}'s loan!",
                    "loan_id": loan.id,
                    "priority": "critical"
                },
                priority="urgent"
            ))

            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.TASK,
                target="loan_officer",
                data={
                    "title": f"Rate lock extension decision for {first_name}",
                    "description": "Lock expiring soon. Review extension costs vs relock options.",
                    "due_hours": 24,
                    "priority": "urgent",
                    "loan_id": loan.id
                },
                priority="urgent"
            ))

        elif trigger == "closing_approaching":
            # Closing countdown
            days_to_close = self._calculate_days_to_close(loan)

            if days_to_close <= 7:
                actions.append(PowerPlayAction(
                    action_type=WorkflowActionType.TASK,
                    target="loan_officer",
                    data={
                        "title": f"Final closing prep for {first_name}",
                        "description": f"Closing in {days_to_close} days. Verify all conditions cleared, CD sent, wire instructions ready.",
                        "due_hours": 24,
                        "priority": "high",
                        "loan_id": loan.id
                    },
                    priority="high"
                ))

                actions.append(PowerPlayAction(
                    action_type=WorkflowActionType.EMAIL,
                    target="borrower",
                    data={
                        "to": getattr(loan, 'borrower_email', None),
                        "subject": f"Closing Week! What to Expect, {first_name}",
                        "template": "closing_week_prep",
                        "borrower_name": borrower_name,
                        "days_to_close": days_to_close
                    }
                ))

        return PowerPlayResult(
            workflow_type=PowerPlayType.UNDER_CONTRACT,
            entity_id=loan.id,
            entity_type="loan",
            actions=actions,
            status="processed",
            message=f"Under Contract Power Play: {len(actions)} actions"
        )

    # ==========================================================================
    # 6. CONSUMER REFERRAL POWER PLAY
    # ==========================================================================

    def _execute_consumer_referral_power_play(self, client: Any, trigger: str) -> PowerPlayResult:
        """
        Consumer Referral Power Play - Past clients with referral potential

        AMR (Annual Mortgage Review) integration
        """
        actions = []
        first_name = client.name.split()[0] if hasattr(client, 'name') and client.name else "there"

        # Get referral score
        referral_score = getattr(client, 'referral_source_score', 0) or 0

        if trigger == "loan_closed":
            # Just closed - initiate referral nurture
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.TAG,
                target="contact",
                data={
                    "contact_id": client.id,
                    "tags": ["past-client", f"referral-score-{referral_score}", "amr-enrolled"]
                }
            ))

            # Send thank you + referral ask (delayed)
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.EMAIL,
                target="contact",
                data={
                    "to": client.email,
                    "subject": f"Congratulations on Your New Home, {first_name}!",
                    "template": "post_close_thank_you",
                    "client_name": client.name
                },
                priority="high"
            ))

            # Referral request (30 days later)
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.EMAIL,
                target="contact",
                data={
                    "to": client.email,
                    "subject": f"{first_name}, Know Someone Looking for a Home?",
                    "template": "referral_request",
                    "client_name": client.name
                },
                scheduled_for=datetime.now(timezone.utc) + timedelta(days=30)
            ))

            # Start post-close drip
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.DRIP_CAMPAIGN,
                target="contact",
                data={
                    "contact_id": client.id,
                    "campaign": "past_client_nurture",
                    "include_amr": True
                }
            ))

        elif trigger == "amr_due":
            # Annual Mortgage Review due
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.TASK,
                target="loan_officer",
                data={
                    "title": f"AMR Call with {first_name}",
                    "description": "Annual Mortgage Review: Check rate environment, equity position, refinance opportunity, referral ask",
                    "due_hours": 168,  # 7 days
                    "priority": "medium",
                    "contact_id": client.id
                }
            ))

            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.EMAIL,
                target="contact",
                data={
                    "to": client.email,
                    "subject": f"Time for Your Annual Mortgage Review, {first_name}",
                    "template": "amr_invitation",
                    "client_name": client.name
                }
            ))

        elif trigger == "referral_received":
            # They sent a referral!
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.EMAIL,
                target="contact",
                data={
                    "to": client.email,
                    "subject": f"Thank You for the Referral, {first_name}!",
                    "template": "referral_thank_you",
                    "client_name": client.name
                },
                priority="high"
            ))

            # Update referral score
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.TAG,
                target="contact",
                data={
                    "contact_id": client.id,
                    "tags": ["active-referrer"],
                    "update_score": referral_score + 10
                }
            ))

        # Schedule next touch based on referral score
        high_value = referral_score >= 70
        next_touch = datetime.now(timezone.utc) + timedelta(days=30 if high_value else 60)

        return PowerPlayResult(
            workflow_type=PowerPlayType.CONSUMER_REFERRAL,
            entity_id=client.id,
            entity_type="contact",
            actions=actions,
            next_touch_date=next_touch,
            status="processed",
            message=f"Consumer Referral Power Play: {len(actions)} actions, score={referral_score}"
        )

    # ==========================================================================
    # 7. CIRCLE OF CASH FLOW POWER PLAY
    # ==========================================================================

    def _execute_circle_of_cash_flow_power_play(self, partner: Any, trigger: str) -> PowerPlayResult:
        """
        Circle of Cash Flow Power Play - Realtor/professional referral management

        Relationship nurturing for referral partners (realtors, CPAs, attorneys, etc.)
        """
        actions = []
        partner_name = (partner.name if hasattr(partner, 'name') else "Partner") or "Partner"
        partner_name = partner_name.strip() or "Partner"
        first_name = partner_name.split()[0]
        partner_type = getattr(partner, 'partner_type', 'realtor')

        if trigger == "new_partner":
            # New referral partner
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.TASK,
                target="loan_officer",
                data={
                    "title": f"Intro meeting with {first_name}",
                    "description": f"Schedule coffee/lunch with new {partner_type} partner. Discuss referral process, communication preferences.",
                    "due_hours": 72,
                    "priority": "high",
                    "partner_id": partner.id
                },
                priority="high"
            ))

            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.TAG,
                target="partner",
                data={
                    "partner_id": partner.id,
                    "tags": [f"partner-{partner_type}", "new-relationship", "nurture-active"]
                }
            ))

            # Start partner nurture campaign
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.DRIP_CAMPAIGN,
                target="partner",
                data={
                    "partner_id": partner.id,
                    "campaign": f"{partner_type}_partner_nurture",
                    "content": ["market_updates", "co_marketing_opportunities", "success_stories"]
                }
            ))

        elif trigger == "referral_sent":
            # Partner sent a referral
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.EMAIL,
                target="partner",
                data={
                    "to": partner.email,
                    "subject": f"Got It! Thanks for the Referral, {first_name}",
                    "template": "partner_referral_received",
                    "partner_name": partner_name
                },
                priority="high"
            ))

            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.TASK,
                target="loan_officer",
                data={
                    "title": f"Update {first_name} on referral status",
                    "description": "Keep partner informed on lead progress. Schedule for 48 hours after initial contact.",
                    "due_hours": 48,
                    "priority": "high",
                    "partner_id": partner.id
                }
            ))

        elif trigger == "deal_closed":
            # Deal from partner closed
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.EMAIL,
                target="partner",
                data={
                    "to": partner.email,
                    "subject": f"We Did It! Closed Another One, {first_name}",
                    "template": "partner_deal_closed",
                    "partner_name": partner_name
                },
                priority="high"
            ))

            # Co-celebration opportunity
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.TASK,
                target="loan_officer",
                data={
                    "title": f"Celebration touchpoint with {first_name}",
                    "description": "Send thank you gift/card, discuss next opportunities, strengthen relationship",
                    "due_hours": 72,
                    "priority": "medium",
                    "partner_id": partner.id
                }
            ))

        elif trigger == "scheduled_touch":
            # Regular relationship maintenance
            actions.append(PowerPlayAction(
                action_type=WorkflowActionType.TASK,
                target="loan_officer",
                data={
                    "title": f"Relationship touch with {first_name}",
                    "description": "Coffee/lunch catch-up. Share market insights, discuss any deals in pipeline.",
                    "due_hours": 168,
                    "priority": "medium",
                    "partner_id": partner.id
                }
            ))

        # Schedule next touch (monthly for active partners)
        next_touch = datetime.now(timezone.utc) + timedelta(days=30)

        return PowerPlayResult(
            workflow_type=PowerPlayType.CIRCLE_OF_CASH_FLOW,
            entity_id=partner.id,
            entity_type="partner",
            actions=actions,
            next_touch_date=next_touch,
            status="processed",
            message=f"Circle of Cash Flow Power Play: {len(actions)} actions for {partner_type}"
        )

    # ==========================================================================
    # HELPER METHODS
    # ==========================================================================

    def _get_varied_touch_type(self, lead: Any) -> str:
        """Get varied touch type to avoid monotony"""
        touch_types = [
            "Check-in call",
            "Market update email",
            "Rate alert",
            "Educational content",
            "Personal touch"
        ]
        # Use lead ID to vary touches
        return touch_types[lead.id % len(touch_types)]

    def _get_milestone_tasks(self, loan: Any, stage: str) -> List[PowerPlayAction]:
        """Get tasks for specific milestone stages"""
        tasks = []
        first_name = (loan.borrower_name or "Borrower").split()[0]

        milestone_config = {
            "Processing": {
                "title": f"Complete initial processing for {first_name}",
                "description": "Order appraisal, title, verify employment/assets",
                "due_hours": 48
            },
            "Submitted": {
                "title": f"Monitor submission for {first_name}",
                "description": "Track underwriting queue position, prepare for conditions",
                "due_hours": 24
            },
            "Underwriting": {
                "title": f"Manage underwriting for {first_name}",
                "description": "Address initial conditions, monitor for additional requests",
                "due_hours": 48
            },
            "Conditional Approval": {
                "title": f"Clear conditions for {first_name}",
                "description": "Collect and submit all outstanding conditions",
                "due_hours": 72
            },
            "CTC": {
                "title": f"Schedule closing for {first_name}",
                "description": "Clear to Close! Coordinate closing date with title, prepare final docs",
                "due_hours": 24
            },
            "Docs Out": {
                "title": f"Verify docs received for {first_name}",
                "description": "Confirm title has closing docs, verify wire instructions",
                "due_hours": 24
            }
        }

        if stage in milestone_config:
            config = milestone_config[stage]
            tasks.append(PowerPlayAction(
                action_type=WorkflowActionType.TASK,
                target="loan_officer",
                data={
                    "title": config["title"],
                    "description": config["description"],
                    "due_hours": config["due_hours"],
                    "priority": "high",
                    "loan_id": loan.id
                },
                priority="high"
            ))

        return tasks

    def _calculate_days_to_close(self, loan: Any) -> int:
        """Calculate days until closing"""
        closing_date = getattr(loan, 'estimated_closing_date', None)
        if closing_date:
            if isinstance(closing_date, datetime):
                delta = closing_date - datetime.now(timezone.utc)
            else:
                delta = datetime.combine(closing_date, datetime.min.time()) - datetime.now()
            return max(0, delta.days)
        return 30  # Default assumption


# ==============================================================================
# WORKFLOW SCHEDULER
# ==============================================================================

class PowerPlayScheduler:
    """Scheduler for time-based Power Play executions"""

    def __init__(self, db: Session):
        self.db = db
        self.engine = PowerPlayEngine(db)

    async def run_scheduled_touches(self) -> List[PowerPlayResult]:
        """Run all scheduled touches that are due"""
        results = []
        now = datetime.now(timezone.utc)

        # Find leads with due touches
        try:
            due_leads = self.db.execute(text("""
                SELECT id, name, email, phone, stage, owner_id,
                       buying_timeline_category, next_touch_date
                FROM leads
                WHERE next_touch_date <= :now
                AND stage NOT IN ('Closed', 'Dead')
            """), {"now": now})

            for lead_row in due_leads.fetchall():
                # Create a simple lead object
                class LeadObj:
                    pass
                lead = LeadObj()
                lead.id = lead_row.id
                lead.name = lead_row.name
                lead.email = lead_row.email
                lead.phone = lead_row.phone
                lead.stage = lead_row.stage
                lead.owner_id = lead_row.owner_id
                lead.buying_timeline_category = lead_row.buying_timeline_category

                result = self.engine.process_lead_workflow(lead, trigger="scheduled_touch")
                results.append(result)

                # Update next touch date
                if result.next_touch_date:
                    self.db.execute(text("""
                        UPDATE leads SET next_touch_date = :next_touch
                        WHERE id = :lead_id
                    """), {"next_touch": result.next_touch_date, "lead_id": lead.id})

            self.db.commit()

        except Exception as e:
            logger.error(f"Error running scheduled touches: {e}")
            self.db.rollback()

        return results

    async def run_amr_checks(self) -> List[PowerPlayResult]:
        """Check for clients due for Annual Mortgage Review"""
        results = []
        now = datetime.now(timezone.utc)

        # Find clients with AMR due (within 30 days of close anniversary)
        try:
            # This would query past clients where close date anniversary is approaching
            pass  # Implementation depends on client/contact model structure
        except Exception as e:
            logger.error(f"Error running AMR checks: {e}")

        return results
