"""
Borrower Portal V2 Service

Enhanced borrower-facing document portal service for Smart Docs V2.
Provides magic-link and access-code authentication, document uploads with
auto-classification, checklist management, loan progress tracking, secure
messaging, e-signature integration, multi-language support, mobile-responsive
data structures, portal analytics, and white-label branding.

Security model:
- Magic link: signed JWT emailed to borrower, 24-hour expiry
- Access code: 6-digit code generated by LO, single-use
- Portal session: JWT with borrower_email, loan_id, org_id claims
- Rate limiting: 5 login attempts per hour per email (in-memory, Redis in prod)

Usage:
    from services.smart_docs.borrower_portal_v2_service import BorrowerPortalV2Service

    svc = BorrowerPortalV2Service(db)
    result = await svc.send_magic_link(email="jane@example.com", loan_id=42, org_id=1)
"""

import hashlib
import logging
import os
import secrets
import time
import uuid
from collections import defaultdict
from datetime import datetime, timezone, timedelta
from typing import Any, Dict, List, Optional, Tuple

import jwt
from sqlalchemy import func, text as sa_text
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import Session

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

SECRET_KEY = os.getenv("SECRET_KEY", "dev-secret-key-change-in-production")
PORTAL_V2_ALGORITHM = "HS256"
PORTAL_V2_ISSUER = "perennia-portal-v2"
PORTAL_V2_TOKEN_EXPIRY_HOURS = 24
PORTAL_BASE_URL = os.getenv("PORTAL_BASE_URL", "https://app.perenniaai.com/portal")

# Upload constraints
MAX_FILE_SIZE_MB = 25
MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024
ALLOWED_MIME_TYPES = frozenset({
    "application/pdf",
    "image/jpeg",
    "image/png",
    "image/tiff",
    "image/heic",
    "image/heif",
    "image/webp",
})
ALLOWED_EXTENSIONS = frozenset({
    ".pdf", ".jpg", ".jpeg", ".png", ".tiff", ".tif",
    ".heic", ".heif", ".webp",
})

# Rate limiting
MAX_LOGIN_ATTEMPTS_PER_HOUR = 5
MAX_UPLOADS_PER_HOUR = 20

# Access code
ACCESS_CODE_LENGTH = 6
ACCESS_CODE_EXPIRY_MINUTES = 60

# In-memory stores (replace with Redis in multi-worker production)
_login_attempt_timestamps: Dict[str, list] = defaultdict(list)
_upload_timestamps: Dict[str, list] = defaultdict(list)
_access_codes: Dict[str, Dict[str, Any]] = {}  # email -> {code, loan_id, org_id, expires_at, attempts}

# Pipeline stage display order and labels
_STAGE_DISPLAY_ORDER = [
    ("APPLICATION", "Application Received"),
    ("DISCLOSED", "Disclosures Sent"),
    ("PROCESSING", "In Processing"),
    ("SUBMITTED", "Submitted to Underwriting"),
    ("UNDERWRITING", "Under Review"),
    ("UW_RECEIVED", "Underwriting Received"),
    ("CONDITIONAL_APPROVAL", "Conditional Approval"),
    ("APPROVED", "Approved"),
    ("CTC", "Clear to Close"),
    ("CLEAR_TO_CLOSE", "Clear to Close"),
    ("CLOSING", "Closing"),
    ("DOCS", "Closing Docs"),
    ("DOCS_OUT", "Docs Out"),
    ("FUNDED", "Funded"),
]

# Multi-language support
_TRANSLATIONS = {
    "en": {
        "checklist_title": "Document Checklist",
        "upload_success": "Document uploaded successfully",
        "upload_next_steps": "Your document is being reviewed. You will be notified when it has been processed.",
        "overdue_warning": "This document is past due. Please upload as soon as possible.",
        "category_income": "Income",
        "category_assets": "Assets",
        "category_identity": "Identity",
        "category_property": "Property",
        "category_credit": "Credit",
        "category_special": "Special",
        "progress_title": "Loan Progress",
        "message_sent": "Message sent successfully",
        "signature_pending": "Signature required",
        "magic_link_subject": "Your Secure Document Portal Link",
        "magic_link_body": "Click the link below to access your document portal. This link expires in 24 hours.",
    },
    "es": {
        "checklist_title": "Lista de Documentos",
        "upload_success": "Documento cargado exitosamente",
        "upload_next_steps": "Su documento esta siendo revisado. Se le notificara cuando haya sido procesado.",
        "overdue_warning": "Este documento esta vencido. Por favor cargue lo antes posible.",
        "category_income": "Ingresos",
        "category_assets": "Activos",
        "category_identity": "Identidad",
        "category_property": "Propiedad",
        "category_credit": "Credito",
        "category_special": "Especial",
        "progress_title": "Progreso del Prestamo",
        "message_sent": "Mensaje enviado exitosamente",
        "signature_pending": "Se requiere firma",
        "magic_link_subject": "Su Enlace Seguro al Portal de Documentos",
        "magic_link_body": "Haga clic en el enlace a continuacion para acceder a su portal de documentos. Este enlace expira en 24 horas.",
    },
}

# Document type to category mapping
_DOC_TYPE_CATEGORIES = {
    "DRIVERS_LICENSE": "identity",
    "PAYSTUB": "income",
    "W2": "income",
    "TAX_RETURN": "income",
    "BUSINESS_TAX_RETURN": "income",
    "PROFIT_LOSS": "income",
    "BALANCE_SHEET": "income",
    "BANK_STATEMENT": "assets",
    "INVESTMENT_STATEMENT": "assets",
    "GIFT_LETTER": "assets",
    "LOE": "special",
    "LEASE_AGREEMENT": "property",
    "FHA_CERT": "special",
    "VA_COE": "special",
    "DD214": "special",
    "BANKRUPTCY_DISCHARGE": "credit",
    "PURCHASE_CONTRACT": "property",
    "APPRAISAL": "property",
    "TITLE_REPORT": "property",
    "HOMEOWNERS_INSURANCE": "property",
    "OTHER": "special",
}


def _mask_email(email: str) -> str:
    """Mask email for logging (e.g., j***n@example.com)."""
    parts = email.split("@")
    if len(parts) != 2:
        return "***"
    local = parts[0]
    domain = parts[1]
    if len(local) <= 2:
        masked = local[0] + "***"
    else:
        masked = local[0] + "***" + local[-1]
    return f"{masked}@{domain}"


def _get_translation(key: str, lang: str = "en") -> str:
    """Get translated string, falling back to English."""
    translations = _TRANSLATIONS.get(lang, _TRANSLATIONS["en"])
    return translations.get(key, _TRANSLATIONS["en"].get(key, key))


# ---------------------------------------------------------------------------
# Portal V2 Token Management
# ---------------------------------------------------------------------------

class PortalV2TokenService:
    """Handles JWT token generation and verification for portal V2 sessions."""

    @staticmethod
    def generate_token(
        loan_id: Any,
        borrower_email: str,
        org_id: Any,
        scope: str = "read_write",
        expires_hours: int = PORTAL_V2_TOKEN_EXPIRY_HOURS,
    ) -> str:
        """
        Generate a signed JWT portal session token.

        Args:
            loan_id: Loan ID the borrower is authorized to access.
            borrower_email: Borrower's email address.
            org_id: Organization ID for tenant isolation.
            scope: "read" or "read_write".
            expires_hours: Token lifetime in hours (default 24).

        Returns:
            Signed JWT string.

        Raises:
            ValueError: If required parameters are missing.
        """
        if not loan_id or not borrower_email or not org_id:
            raise ValueError("loan_id, borrower_email, and org_id are required")

        email_lower = borrower_email.strip().lower()
        now = datetime.now(timezone.utc)
        expires_at = now + timedelta(hours=expires_hours)

        payload = {
            "iss": PORTAL_V2_ISSUER,
            "sub": email_lower,
            "loan_id": str(loan_id),
            "org_id": str(org_id),
            "scope": scope,
            "version": "v2",
            "jti": str(uuid.uuid4()),
            "iat": int(now.timestamp()),
            "exp": int(expires_at.timestamp()),
        }

        token = jwt.encode(payload, SECRET_KEY, algorithm=PORTAL_V2_ALGORITHM)
        logger.info(
            f"Portal V2 token generated for {_mask_email(email_lower)}, "
            f"loan={loan_id}, org={org_id}, expires={expires_at.isoformat()}"
        )
        return token

    @staticmethod
    def verify_token(token: str) -> Dict[str, Any]:
        """
        Verify a portal V2 token and return decoded claims.

        Returns:
            Dict with loan_id, borrower_email, org_id, scope, issued_at, expires_at.

        Raises:
            ValueError: If the token is invalid, expired, or malformed.
        """
        if not token:
            raise ValueError("Portal access token is required")

        try:
            payload = jwt.decode(
                token,
                SECRET_KEY,
                algorithms=[PORTAL_V2_ALGORITHM],
                issuer=PORTAL_V2_ISSUER,
                options={"require": ["exp", "iss", "sub", "loan_id", "org_id"]},
            )
        except jwt.ExpiredSignatureError:
            raise ValueError("Portal session has expired. Please request a new link.")
        except jwt.InvalidIssuerError:
            raise ValueError("Invalid portal token")
        except jwt.DecodeError:
            raise ValueError("Invalid portal token")
        except jwt.MissingRequiredClaimError:
            raise ValueError("Invalid portal token")
        except jwt.InvalidTokenError:
            raise ValueError("Invalid portal token")

        return {
            "loan_id": payload["loan_id"],
            "borrower_email": payload["sub"],
            "org_id": payload["org_id"],
            "scope": payload.get("scope", "read"),
            "jti": payload.get("jti"),
            "issued_at": datetime.fromtimestamp(payload["iat"], tz=timezone.utc).isoformat(),
            "expires_at": datetime.fromtimestamp(payload["exp"], tz=timezone.utc).isoformat(),
        }


# ---------------------------------------------------------------------------
# Rate Limiting
# ---------------------------------------------------------------------------

class PortalRateLimiter:
    """In-memory rate limiter for portal login and upload operations."""

    @staticmethod
    def check_login_rate_limit(email: str) -> None:
        """
        Enforce login rate limiting: max 5 attempts per hour per email.

        Raises:
            ValueError: If rate limit exceeded.
        """
        email_lower = email.strip().lower()
        now = time.time()
        cutoff = now - 3600

        _login_attempt_timestamps[email_lower] = [
            ts for ts in _login_attempt_timestamps[email_lower] if ts > cutoff
        ]

        if len(_login_attempt_timestamps[email_lower]) >= MAX_LOGIN_ATTEMPTS_PER_HOUR:
            logger.warning(f"Portal V2 login rate limit exceeded for {_mask_email(email_lower)}")
            raise ValueError("Too many login attempts. Please try again later.")

        _login_attempt_timestamps[email_lower].append(now)

    @staticmethod
    def check_upload_rate_limit(email: str) -> None:
        """
        Enforce upload rate limiting: max 20 uploads per hour per borrower.

        Raises:
            ValueError: If rate limit exceeded.
        """
        email_lower = email.strip().lower()
        now = time.time()
        cutoff = now - 3600

        _upload_timestamps[email_lower] = [
            ts for ts in _upload_timestamps[email_lower] if ts > cutoff
        ]

        if len(_upload_timestamps[email_lower]) >= MAX_UPLOADS_PER_HOUR:
            logger.warning(f"Portal V2 upload rate limit exceeded for {_mask_email(email_lower)}")
            raise ValueError("Upload rate limit exceeded. Please try again later.")

        _upload_timestamps[email_lower].append(now)

    @staticmethod
    def reset_all() -> None:
        """Reset all rate limit counters. For testing only."""
        _login_attempt_timestamps.clear()
        _upload_timestamps.clear()
        _access_codes.clear()


# ---------------------------------------------------------------------------
# Access Code Management
# ---------------------------------------------------------------------------

class AccessCodeService:
    """Manages 6-digit access codes issued by LOs for borrower portal login."""

    @staticmethod
    def generate_access_code(
        borrower_email: str,
        loan_id: Any,
        org_id: Any,
        expires_minutes: int = ACCESS_CODE_EXPIRY_MINUTES,
    ) -> str:
        """
        Generate a 6-digit access code for a borrower.

        The LO provides this code to the borrower (via phone, text, etc.)
        who then enters it on the portal login screen.

        Args:
            borrower_email: Borrower's email.
            loan_id: Associated loan ID.
            org_id: Organization ID.
            expires_minutes: Code expiry in minutes.

        Returns:
            6-digit access code string.
        """
        email_lower = borrower_email.strip().lower()
        code = "".join([str(secrets.randbelow(10)) for _ in range(ACCESS_CODE_LENGTH)])
        expires_at = datetime.now(timezone.utc) + timedelta(minutes=expires_minutes)

        _access_codes[email_lower] = {
            "code": code,
            "loan_id": str(loan_id),
            "org_id": str(org_id),
            "expires_at": expires_at,
            "attempts": 0,
            "max_attempts": 5,
            "created_at": datetime.now(timezone.utc),
        }

        logger.info(
            f"Access code generated for {_mask_email(email_lower)}, "
            f"loan={loan_id}, expires={expires_at.isoformat()}"
        )
        return code

    @staticmethod
    def verify_access_code(
        borrower_email: str,
        code: str,
    ) -> Dict[str, Any]:
        """
        Verify a 6-digit access code.

        Args:
            borrower_email: Borrower's email.
            code: The 6-digit code to verify.

        Returns:
            Dict with loan_id and org_id on success.

        Raises:
            ValueError: If code is invalid, expired, or max attempts exceeded.
        """
        email_lower = borrower_email.strip().lower()

        stored = _access_codes.get(email_lower)
        if not stored:
            raise ValueError("No access code found. Please request a new code from your loan officer.")

        # Check expiry
        if datetime.now(timezone.utc) > stored["expires_at"]:
            del _access_codes[email_lower]
            raise ValueError("Access code has expired. Please request a new code from your loan officer.")

        # Check max attempts
        stored["attempts"] += 1
        if stored["attempts"] > stored["max_attempts"]:
            del _access_codes[email_lower]
            raise ValueError("Too many incorrect attempts. Please request a new code.")

        # Constant-time comparison to prevent timing attacks
        if not secrets.compare_digest(code.strip(), stored["code"]):
            remaining = stored["max_attempts"] - stored["attempts"]
            raise ValueError(f"Invalid access code. {remaining} attempts remaining.")

        # Code is valid - consume it (single-use)
        result = {
            "loan_id": stored["loan_id"],
            "org_id": stored["org_id"],
        }
        del _access_codes[email_lower]
        return result


# ---------------------------------------------------------------------------
# Upload Validation
# ---------------------------------------------------------------------------

class UploadValidator:
    """Validates document uploads for portal V2."""

    @staticmethod
    def validate_upload(
        filename: str,
        content_type: str,
        file_size: int,
    ) -> Dict[str, Any]:
        """
        Validate an upload file for type, size, and extension.

        Args:
            filename: Original filename.
            content_type: MIME type of the upload.
            file_size: Size in bytes.

        Returns:
            Dict with validation result and details.

        Raises:
            ValueError: If validation fails.
        """
        issues = []

        # Extension check
        ext = ""
        if "." in filename:
            ext = "." + filename.rsplit(".", 1)[-1].lower()
        if ext not in ALLOWED_EXTENSIONS:
            issues.append(
                f"File type '{ext or 'unknown'}' is not supported. "
                f"Accepted: PDF, JPG, PNG, TIFF, HEIC"
            )

        # MIME type check
        if content_type and content_type.lower() not in ALLOWED_MIME_TYPES:
            issues.append(
                f"Content type '{content_type}' is not supported."
            )

        # Size check
        if file_size > MAX_FILE_SIZE_BYTES:
            issues.append(
                f"File is too large ({file_size / (1024 * 1024):.1f} MB). "
                f"Maximum size is {MAX_FILE_SIZE_MB} MB."
            )

        if file_size == 0:
            issues.append("File is empty.")

        if issues:
            raise ValueError(" ".join(issues))

        return {
            "valid": True,
            "filename": filename,
            "extension": ext,
            "content_type": content_type,
            "file_size": file_size,
            "file_size_display": f"{file_size / (1024 * 1024):.2f} MB" if file_size >= 1024 * 1024 else f"{file_size / 1024:.1f} KB",
        }

    @staticmethod
    def assess_image_quality(file_bytes: bytes, content_type: str) -> Dict[str, Any]:
        """
        Assess image quality for readability (basic heuristic checks).

        For images, checks minimum resolution threshold via file size.
        Full OCR quality analysis happens downstream in the AI review pipeline.

        Returns:
            Dict with quality assessment.
        """
        quality = {
            "acceptable": True,
            "warnings": [],
        }

        if content_type and content_type.startswith("image/"):
            # Very small images are likely too low resolution
            if len(file_bytes) < 50_000:  # < 50KB
                quality["warnings"].append(
                    "Image appears to be low resolution. Please ensure the document is clearly readable."
                )
            # Very large uncompressed images might be photos of screens
            if len(file_bytes) > 15_000_000:  # > 15MB
                quality["warnings"].append(
                    "Image is very large. Consider taking a clearer, cropped photo."
                )

        return quality


# ---------------------------------------------------------------------------
# Main Service
# ---------------------------------------------------------------------------

class BorrowerPortalV2Service:
    """
    Core service for the borrower document portal V2.

    Coordinates authentication, document management, messaging, e-signatures,
    progress tracking, and analytics for the borrower-facing portal.
    """

    def __init__(self, db: Session):
        self.db = db
        self.token_service = PortalV2TokenService()
        self.rate_limiter = PortalRateLimiter()
        self.access_code_service = AccessCodeService()
        self.upload_validator = UploadValidator()

    # -----------------------------------------------------------------------
    # Authentication
    # -----------------------------------------------------------------------

    async def send_magic_link(
        self,
        borrower_email: str,
        loan_id: int,
        org_id: int,
        lang: str = "en",
    ) -> Dict[str, Any]:
        """
        Send a magic link to the borrower's email for portal access.

        Validates the borrower exists on the loan, generates a 24-hour token,
        and constructs the magic link URL.  Email delivery is delegated to
        the caller (routes layer) since the email service is async.

        Args:
            borrower_email: Borrower's email address.
            loan_id: The loan to grant access to.
            org_id: Organization ID for tenant isolation.
            lang: Language code ("en" or "es").

        Returns:
            Dict with magic_link_url, token, expires_at, email_subject, email_body.

        Raises:
            ValueError: If rate limited or borrower not found.
        """
        email_lower = borrower_email.strip().lower()

        # Rate limit
        self.rate_limiter.check_login_rate_limit(email_lower)

        # Verify borrower exists on this loan in this org
        borrower_info = await self._verify_borrower_on_loan(email_lower, loan_id, org_id)

        # Generate token
        token = self.token_service.generate_token(
            loan_id=loan_id,
            borrower_email=email_lower,
            org_id=org_id,
            scope="read_write",
        )

        # Build magic link URL
        magic_link_url = f"{PORTAL_BASE_URL}/v2/auth?token={token}"

        # Get branding
        branding = await self._get_org_branding(org_id)

        # Build email content
        subject = _get_translation("magic_link_subject", lang)
        body = _get_translation("magic_link_body", lang)

        claims = self.token_service.verify_token(token)

        return {
            "magic_link_url": magic_link_url,
            "token": token,
            "expires_at": claims["expires_at"],
            "borrower_name": borrower_info.get("name", ""),
            "email_subject": subject,
            "email_body": body,
            "branding": branding,
            "lang": lang,
        }

    async def verify_auth(
        self,
        email: Optional[str] = None,
        token: Optional[str] = None,
        access_code: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Verify portal authentication via magic link token or access code.

        Exactly one of token or access_code must be provided.

        Args:
            email: Borrower email (required for access_code auth).
            token: JWT token from magic link.
            access_code: 6-digit access code from LO.

        Returns:
            Dict with session_token, borrower_email, loan_id, org_id, expires_at.

        Raises:
            ValueError: If authentication fails.
        """
        if token:
            # Magic link verification
            claims = self.token_service.verify_token(token)
            # Token is already a valid session token
            return {
                "session_token": token,
                "borrower_email": claims["borrower_email"],
                "loan_id": claims["loan_id"],
                "org_id": claims["org_id"],
                "scope": claims["scope"],
                "expires_at": claims["expires_at"],
                "auth_method": "magic_link",
            }

        elif access_code and email:
            email_lower = email.strip().lower()

            # Rate limit
            self.rate_limiter.check_login_rate_limit(email_lower)

            # Verify access code
            code_claims = self.access_code_service.verify_access_code(email_lower, access_code)

            # Generate a fresh session token
            session_token = self.token_service.generate_token(
                loan_id=code_claims["loan_id"],
                borrower_email=email_lower,
                org_id=code_claims["org_id"],
                scope="read_write",
            )

            token_claims = self.token_service.verify_token(session_token)

            return {
                "session_token": session_token,
                "borrower_email": email_lower,
                "loan_id": code_claims["loan_id"],
                "org_id": code_claims["org_id"],
                "scope": "read_write",
                "expires_at": token_claims["expires_at"],
                "auth_method": "access_code",
            }

        else:
            raise ValueError("Either token or (email + access_code) is required for authentication.")

    # -----------------------------------------------------------------------
    # Document Checklist
    # -----------------------------------------------------------------------

    async def get_checklist(
        self,
        loan_id: str,
        org_id: str,
        lang: str = "en",
    ) -> Dict[str, Any]:
        """
        Get the document checklist for a loan, grouped by category.

        Returns outstanding items with priority, completed items with timestamps,
        due dates, overdue warnings, and category grouping.

        Args:
            loan_id: Loan ID.
            org_id: Organization ID for tenant isolation.
            lang: Language code.

        Returns:
            Dict with categories, summary stats, and individual items.
        """
        # Fetch all active document requests for this loan
        requests_rows = self.db.execute(
            sa_text("""
                SELECT
                    sdr.id, sdr.doc_type, sdr.title, sdr.description,
                    sdr.instructions, sdr.priority, sdr.status,
                    sdr.due_date, sdr.completed_at, sdr.required_count,
                    sdr.created_at
                FROM smart_document_requests sdr
                JOIN loans l ON l.id = sdr.loan_id
                WHERE sdr.loan_id = :loan_id
                    AND l.organization_id = :org_id
                    AND sdr.is_active = true
                ORDER BY
                    CASE sdr.priority
                        WHEN 'CRITICAL' THEN 1
                        WHEN 'HIGH' THEN 2
                        WHEN 'NORMAL' THEN 3
                        WHEN 'LOW' THEN 4
                        ELSE 5
                    END,
                    sdr.created_at ASC
            """),
            {"loan_id": int(loan_id), "org_id": int(org_id)},
        ).fetchall()

        # Fetch uploaded documents grouped by request_id
        uploaded_rows = self.db.execute(
            sa_text("""
                SELECT
                    sd.id, sd.request_id, sd.file_name, sd.display_name,
                    sd.status, sd.decision, sd.uploaded_at,
                    sd.rejection_reason, sd.fix_instructions,
                    sd.detected_doc_type, sd.doc_type
                FROM smart_documents sd
                WHERE sd.loan_id = :loan_id
                    AND sd.status NOT IN ('DELETED', 'SUPERSEDED')
                ORDER BY sd.uploaded_at DESC
            """),
            {"loan_id": int(loan_id)},
        ).fetchall()

        # Index uploaded docs by request_id
        docs_by_request: Dict[int, List[Dict]] = defaultdict(list)
        for row in uploaded_rows:
            docs_by_request[row[1]].append({
                "document_id": row[0],
                "request_id": row[1],
                "file_name": row[3] or row[2],  # display_name or file_name
                "status": row[4],
                "decision": row[5],
                "uploaded_at": row[6].isoformat() if row[6] else None,
                "rejection_reason": row[7],
                "fix_instructions": row[8],
            })

        # Build categorized checklist
        categories: Dict[str, List[Dict]] = defaultdict(list)
        total_items = 0
        completed_items = 0
        overdue_items = 0
        now = datetime.now(timezone.utc)

        for req_row in requests_rows:
            req_id = req_row[0]
            doc_type = req_row[1]
            status = req_row[6]
            due_date = req_row[7]
            completed_at = req_row[8]

            # Determine category
            doc_type_str = doc_type.value if hasattr(doc_type, "value") else str(doc_type) if doc_type else "OTHER"
            category_key = _DOC_TYPE_CATEGORIES.get(doc_type_str, "special")
            category_label = _get_translation(f"category_{category_key}", lang)

            # Check overdue
            is_overdue = False
            if due_date and status not in ("ACCEPTED", "WAIVED") and due_date < now:
                is_overdue = True
                overdue_items += 1

            # Check completion
            is_completed = status in ("ACCEPTED", "WAIVED")
            if is_completed:
                completed_items += 1
            total_items += 1

            # Priority indicator for mobile
            priority_val = req_row[5]
            priority_str = priority_val.value if hasattr(priority_val, "value") else str(priority_val) if priority_val else "NORMAL"
            priority_indicators = {
                "CRITICAL": {"level": 1, "color": "#dc2626", "icon": "priority_high"},
                "HIGH": {"level": 2, "color": "#f59e0b", "icon": "arrow_upward"},
                "NORMAL": {"level": 3, "color": "#6b7280", "icon": "remove"},
                "LOW": {"level": 4, "color": "#9ca3af", "icon": "arrow_downward"},
            }

            item = {
                "request_id": req_id,
                "doc_type": doc_type_str,
                "title": req_row[2],
                "description": req_row[3],
                "instructions": req_row[4],
                "priority": priority_str,
                "priority_indicator": priority_indicators.get(priority_str, priority_indicators["NORMAL"]),
                "status": status.value if hasattr(status, "value") else str(status),
                "is_completed": is_completed,
                "is_overdue": is_overdue,
                "overdue_warning": _get_translation("overdue_warning", lang) if is_overdue else None,
                "due_date": due_date.isoformat() if due_date else None,
                "completed_at": completed_at.isoformat() if completed_at else None,
                "required_count": req_row[9] or 1,
                "uploaded_documents": docs_by_request.get(req_id, []),
                "uploaded_count": len(docs_by_request.get(req_id, [])),
            }
            categories[category_label].append(item)

        # Build response with mobile-friendly structure
        categories_list = []
        for cat_name, items in categories.items():
            cat_completed = sum(1 for i in items if i["is_completed"])
            categories_list.append({
                "name": cat_name,
                "items": items,
                "total_count": len(items),
                "completed_count": cat_completed,
                "progress_pct": round((cat_completed / len(items)) * 100) if items else 0,
            })

        # Sort categories: Income first, then Assets, Identity, Property, Credit, Special
        category_order = {
            _get_translation("category_income", lang): 0,
            _get_translation("category_assets", lang): 1,
            _get_translation("category_identity", lang): 2,
            _get_translation("category_property", lang): 3,
            _get_translation("category_credit", lang): 4,
            _get_translation("category_special", lang): 5,
        }
        categories_list.sort(key=lambda c: category_order.get(c["name"], 99))

        return {
            "title": _get_translation("checklist_title", lang),
            "loan_id": loan_id,
            "categories": categories_list,
            "summary": {
                "total_items": total_items,
                "completed_items": completed_items,
                "remaining_items": total_items - completed_items,
                "overdue_items": overdue_items,
                "completion_pct": round((completed_items / total_items) * 100) if total_items else 0,
            },
            "lang": lang,
        }

    # -----------------------------------------------------------------------
    # Document Upload
    # -----------------------------------------------------------------------

    async def process_upload(
        self,
        file_bytes: bytes,
        filename: str,
        content_type: str,
        loan_id: str,
        org_id: str,
        borrower_email: str,
        request_id: Optional[int] = None,
        doc_type_hint: Optional[str] = None,
        upload_source: str = "WEB",
        camera_capture: bool = False,
        lang: str = "en",
    ) -> Dict[str, Any]:
        """
        Process a document upload from the borrower portal.

        Validates the file, stores it, queues for AI classification and review,
        and returns upload confirmation with next-steps guidance.

        Args:
            file_bytes: Raw file content.
            filename: Original filename.
            content_type: MIME type.
            loan_id: Loan ID.
            org_id: Organization ID.
            borrower_email: Uploading borrower's email.
            request_id: Optional document request ID this fulfills.
            doc_type_hint: Optional document type hint from borrower.
            upload_source: "WEB", "MOBILE", or "EMAIL".
            camera_capture: Whether this was captured via camera (mobile).
            lang: Language code.

        Returns:
            Dict with upload confirmation, document_id, next steps.

        Raises:
            ValueError: If validation fails or rate limited.
        """
        # Rate limit
        self.rate_limiter.check_upload_rate_limit(borrower_email)

        # Validate
        validation = self.upload_validator.validate_upload(
            filename=filename,
            content_type=content_type,
            file_size=len(file_bytes),
        )

        # Quality assessment for images
        quality = self.upload_validator.assess_image_quality(file_bytes, content_type)

        # Compute file hash
        file_hash = hashlib.sha256(file_bytes).hexdigest()

        # Check for duplicate upload on this loan
        duplicate_check = self.db.execute(
            sa_text("""
                SELECT id, file_name, uploaded_at
                FROM smart_documents
                WHERE loan_id = :loan_id
                    AND storage_key LIKE :hash_pattern
                    AND status NOT IN ('DELETED', 'SUPERSEDED')
                LIMIT 1
            """),
            {"loan_id": int(loan_id), "hash_pattern": f"%{file_hash[:16]}%"},
        ).fetchone()

        is_duplicate = duplicate_check is not None

        # Attempt AI classification if no type hint provided
        classification_result = None
        if not doc_type_hint:
            try:
                from services.smart_docs.ai_classifier_service import get_ai_classifier_service
                classifier = get_ai_classifier_service()
                classification_result = classifier.classify_document(
                    file_bytes, content_type, filename
                )
                if classification_result and classification_result.confidence >= 70:
                    doc_type_hint = classification_result.predicted_type
            except Exception as e:
                logger.warning(f"AI classification failed during upload, continuing: {e}")

        # Store document via upload pipeline
        storage_key = f"smart-docs/{org_id}/{loan_id}/{file_hash[:16]}_{filename}"

        try:
            from services.smart_docs.s3_storage_service import get_smart_docs_s3_service
            s3 = get_smart_docs_s3_service()
            s3.upload_file(
                file_data=file_bytes,
                storage_key=storage_key,
                content_type=content_type,
                metadata={
                    "loan_id": str(loan_id),
                    "org_id": str(org_id),
                    "borrower_email": borrower_email,
                    "upload_source": upload_source,
                    "camera_capture": str(camera_capture),
                },
            )
        except Exception as e:
            logger.error(f"S3 upload failed for loan {loan_id}: {e}")
            raise ValueError("Document upload failed. Please try again.")

        # Resolve borrower_id from email
        borrower_id_row = self.db.execute(
            sa_text("""
                SELECT id FROM borrower_profiles
                WHERE email = :email
                LIMIT 1
            """),
            {"email": borrower_email.strip().lower()},
        ).fetchone()
        borrower_id = borrower_id_row[0] if borrower_id_row else 0

        # Insert SmartDocument record
        now_ts = datetime.now(timezone.utc)
        insert_result = self.db.execute(
            sa_text("""
                INSERT INTO smart_documents (
                    request_id, loan_id, borrower_id, file_name, original_filename,
                    mime_type, file_size, storage_key, doc_type, detected_doc_type,
                    status, upload_source, uploaded_at, created_at, updated_at
                ) VALUES (
                    :request_id, :loan_id, :borrower_id, :file_name, :original_filename,
                    :mime_type, :file_size, :storage_key, :doc_type, :detected_doc_type,
                    'UPLOADED', :upload_source, :uploaded_at, :created_at, :updated_at
                ) RETURNING id
            """),
            {
                "request_id": request_id,
                "loan_id": int(loan_id),
                "borrower_id": borrower_id,
                "file_name": filename,
                "original_filename": filename,
                "mime_type": content_type,
                "file_size": len(file_bytes),
                "storage_key": storage_key,
                "doc_type": doc_type_hint,
                "detected_doc_type": (
                    classification_result.predicted_type if classification_result else None
                ),
                "upload_source": upload_source,
                "uploaded_at": now_ts,
                "created_at": now_ts,
                "updated_at": now_ts,
            },
        )
        doc_id = insert_result.fetchone()[0]
        self.db.commit()

        # If fulfilling a specific request, update its status
        if request_id:
            self.db.execute(
                sa_text("""
                    UPDATE smart_document_requests
                    SET status = 'PENDING_REVIEW', updated_at = :now
                    WHERE id = :request_id AND status = 'OPEN'
                """),
                {"request_id": request_id, "now": now_ts},
            )
            self.db.commit()

        # Log analytics event
        await self._log_portal_event(
            loan_id=loan_id,
            org_id=org_id,
            event_type="document_uploaded",
            borrower_email=borrower_email,
            metadata={
                "document_id": doc_id,
                "doc_type": doc_type_hint,
                "file_size": len(file_bytes),
                "upload_source": upload_source,
                "camera_capture": camera_capture,
                "is_duplicate": is_duplicate,
            },
        )

        return {
            "success": True,
            "document_id": doc_id,
            "filename": filename,
            "file_size": validation["file_size_display"],
            "doc_type": doc_type_hint,
            "classification": {
                "predicted_type": classification_result.predicted_type if classification_result else None,
                "confidence": classification_result.confidence if classification_result else None,
            } if classification_result else None,
            "quality": quality,
            "is_duplicate": is_duplicate,
            "status": "UPLOADED",
            "message": _get_translation("upload_success", lang),
            "next_steps": _get_translation("upload_next_steps", lang),
            "upload_metadata": {
                "source": upload_source,
                "camera_capture": camera_capture,
                "timestamp": now_ts.isoformat(),
            },
        }

    # -----------------------------------------------------------------------
    # Loan Progress Tracker
    # -----------------------------------------------------------------------

    async def get_loan_progress(
        self,
        loan_id: str,
        org_id: str,
        lang: str = "en",
    ) -> Dict[str, Any]:
        """
        Get loan progress for the borrower portal, including pipeline stage,
        estimated closing date, and recent activity feed.

        Returns a mobile-friendly data structure with visual stage indicators.

        Args:
            loan_id: Loan ID.
            org_id: Organization ID.
            lang: Language code.

        Returns:
            Dict with stages, current_stage, estimated_close, activities.
        """
        loan = self.db.execute(
            sa_text("""
                SELECT
                    l.id, l.loan_number, l.borrower_name, l.stage,
                    l.closing_date, l.predicted_close_date,
                    l.property_address, l.amount, l.rate,
                    l.loan_type, l.loan_officer_name,
                    l.stage_changed_at, l.created_at
                FROM loans l
                WHERE l.id = :loan_id AND l.organization_id = :org_id
            """),
            {"loan_id": int(loan_id), "org_id": int(org_id)},
        ).fetchone()

        if not loan:
            raise ValueError("Loan not found")

        current_stage = loan[3] or "APPLICATION"

        # Build stage progress indicator
        stages = []
        current_found = False
        for stage_key, stage_label in _STAGE_DISPLAY_ORDER:
            is_current = (stage_key == current_stage)
            if is_current:
                current_found = True
            # CTC and CLEAR_TO_CLOSE are the same stage
            if stage_key == "CTC" and current_stage == "CLEAR_TO_CLOSE":
                is_current = True
                current_found = True

            status = "completed" if not current_found and not is_current else (
                "current" if is_current else "upcoming"
            )
            # If we hit current, everything before was completed
            stages.append({
                "key": stage_key,
                "label": stage_label,
                "status": status,
                "is_current": is_current,
            })

        # Fix: mark all stages before current as completed
        for i, stage in enumerate(stages):
            if stage["is_current"]:
                for j in range(i):
                    stages[j]["status"] = "completed"
                break

        # Terminal stages
        terminal_stages = ("FUNDED", "CANCELLED", "DENIED", "DEAD", "WITHDRAWN", "DOES_NOT_QUALIFY")
        if current_stage in terminal_stages and current_stage == "FUNDED":
            for stage in stages:
                stage["status"] = "completed"

        # Estimated closing date
        estimated_close = loan[4] or loan[5]  # closing_date or predicted_close_date
        days_to_close = None
        if estimated_close:
            if hasattr(estimated_close, "date"):
                close_date = estimated_close.date()
            else:
                close_date = estimated_close
            today = datetime.now(timezone.utc).date()
            days_to_close = (close_date - today).days
            if days_to_close < 0:
                days_to_close = None  # Past estimated close

        # Recent activity feed
        activities = await self._get_recent_activities(loan_id, limit=10)

        return {
            "title": _get_translation("progress_title", lang),
            "loan_id": loan_id,
            "loan_number": loan[1],
            "borrower_name": loan[2],
            "current_stage": current_stage,
            "current_stage_label": next(
                (s["label"] for s in stages if s["is_current"]), current_stage
            ),
            "stages": stages,
            "progress_pct": self._calculate_progress_pct(current_stage),
            "property_address": loan[6],
            "loan_amount": float(loan[7]) if loan[7] else None,
            "interest_rate": float(loan[8]) if loan[8] else None,
            "loan_type": loan[9],
            "loan_officer_name": loan[10],
            "estimated_closing_date": estimated_close.isoformat() if estimated_close else None,
            "days_to_close": days_to_close,
            "stage_entered_at": loan[11].isoformat() if loan[11] else None,
            "recent_activities": activities,
            "lang": lang,
        }

    # -----------------------------------------------------------------------
    # Secure Messaging
    # -----------------------------------------------------------------------

    async def get_messages(
        self,
        loan_id: str,
        org_id: str,
        borrower_email: str,
        limit: int = 50,
        offset: int = 0,
    ) -> Dict[str, Any]:
        """
        Get messages between borrower and LO for a loan.

        Returns messages with read receipts and file attachment metadata.

        Args:
            loan_id: Loan ID.
            org_id: Organization ID.
            borrower_email: Borrower's email (for read receipt tracking).
            limit: Max messages to return.
            offset: Pagination offset.

        Returns:
            Dict with messages list and unread count.
        """
        messages = self.db.execute(
            sa_text("""
                SELECT
                    pm.id, pm.sender_type, pm.sender_name, pm.sender_email,
                    pm.message_text, pm.attachment_filename, pm.attachment_storage_key,
                    pm.is_read, pm.read_at, pm.created_at,
                    pm.related_request_id
                FROM portal_messages pm
                WHERE pm.loan_id = :loan_id AND pm.org_id = :org_id
                ORDER BY pm.created_at DESC
                LIMIT :limit OFFSET :offset
            """),
            {
                "loan_id": int(loan_id),
                "org_id": int(org_id),
                "limit": limit,
                "offset": offset,
            },
        ).fetchall()

        # Mark unread messages from LO as read
        email_lower = borrower_email.strip().lower()
        self.db.execute(
            sa_text("""
                UPDATE portal_messages
                SET is_read = true, read_at = :now
                WHERE loan_id = :loan_id
                    AND org_id = :org_id
                    AND sender_type = 'lo'
                    AND is_read = false
            """),
            {
                "loan_id": int(loan_id),
                "org_id": int(org_id),
                "now": datetime.now(timezone.utc),
            },
        )
        self.db.commit()

        # Count unread
        unread_row = self.db.execute(
            sa_text("""
                SELECT COUNT(*)
                FROM portal_messages
                WHERE loan_id = :loan_id AND org_id = :org_id
                    AND sender_type = 'lo' AND is_read = false
            """),
            {"loan_id": int(loan_id), "org_id": int(org_id)},
        ).fetchone()
        unread_count = unread_row[0] if unread_row else 0

        messages_list = []
        for row in messages:
            msg = {
                "id": row[0],
                "sender_type": row[1],  # "borrower" or "lo"
                "sender_name": row[2],
                "sender_email": row[3],
                "message": row[4],
                "has_attachment": bool(row[5]),
                "attachment_filename": row[5],
                "is_read": row[7],
                "read_at": row[8].isoformat() if row[8] else None,
                "created_at": row[9].isoformat() if row[9] else None,
                "related_request_id": row[10],
            }
            messages_list.append(msg)

        return {
            "loan_id": loan_id,
            "messages": messages_list,
            "total_count": len(messages_list),
            "unread_count": unread_count,
            "has_more": len(messages_list) == limit,
        }

    async def send_message(
        self,
        loan_id: str,
        org_id: str,
        borrower_email: str,
        borrower_name: str,
        message_text: str,
        related_request_id: Optional[int] = None,
        attachment_filename: Optional[str] = None,
        attachment_storage_key: Optional[str] = None,
        lang: str = "en",
    ) -> Dict[str, Any]:
        """
        Send a message from the borrower to the LO.

        Args:
            loan_id: Loan ID.
            org_id: Organization ID.
            borrower_email: Sender's email.
            borrower_name: Sender's name.
            message_text: Message content.
            related_request_id: Optional document request this relates to.
            attachment_filename: Optional attachment filename.
            attachment_storage_key: Optional S3 key for attachment.
            lang: Language code.

        Returns:
            Dict with message_id and confirmation.
        """
        if not message_text or not message_text.strip():
            raise ValueError("Message cannot be empty")

        if len(message_text) > 5000:
            raise ValueError("Message exceeds maximum length of 5000 characters")

        now_ts = datetime.now(timezone.utc)

        result = self.db.execute(
            sa_text("""
                INSERT INTO portal_messages (
                    loan_id, org_id, sender_type, sender_name, sender_email,
                    message_text, related_request_id,
                    attachment_filename, attachment_storage_key,
                    is_read, created_at
                ) VALUES (
                    :loan_id, :org_id, 'borrower', :sender_name, :sender_email,
                    :message_text, :related_request_id,
                    :attachment_filename, :attachment_storage_key,
                    false, :created_at
                ) RETURNING id
            """),
            {
                "loan_id": int(loan_id),
                "org_id": int(org_id),
                "sender_name": borrower_name,
                "sender_email": borrower_email.strip().lower(),
                "message_text": message_text.strip(),
                "related_request_id": related_request_id,
                "attachment_filename": attachment_filename,
                "attachment_storage_key": attachment_storage_key,
                "created_at": now_ts,
            },
        )
        message_id = result.fetchone()[0]
        self.db.commit()

        # Log analytics event
        await self._log_portal_event(
            loan_id=loan_id,
            org_id=org_id,
            event_type="message_sent",
            borrower_email=borrower_email,
            metadata={"message_id": message_id, "has_attachment": bool(attachment_filename)},
        )

        return {
            "message_id": message_id,
            "message": _get_translation("message_sent", lang),
            "created_at": now_ts.isoformat(),
        }

    # -----------------------------------------------------------------------
    # E-Signature Integration
    # -----------------------------------------------------------------------

    async def get_pending_signatures(
        self,
        loan_id: str,
        org_id: str,
        borrower_email: str,
        lang: str = "en",
    ) -> Dict[str, Any]:
        """
        Get pending e-signature envelopes for a borrower.

        Returns envelopes where the borrower is a recipient with pending status.

        Args:
            loan_id: Loan ID.
            org_id: Organization ID.
            borrower_email: Borrower's email.
            lang: Language code.

        Returns:
            Dict with pending signatures list.
        """
        email_lower = borrower_email.strip().lower()

        envelopes = self.db.execute(
            sa_text("""
                SELECT
                    e.id, e.envelope_uuid, e.title, e.status AS envelope_status,
                    e.created_at, e.expires_at, e.document_name,
                    r.id AS recipient_id, r.status AS recipient_status,
                    r.signing_url, r.viewed_at, r.signed_at, r.auth_method
                FROM esignature_envelopes e
                JOIN esignature_recipients r
                    ON r.envelope_id = e.id
                WHERE e.loan_id = :loan_id
                    AND e.organization_id = :org_id
                    AND r.email = :email
                    AND e.status NOT IN ('voided', 'expired', 'completed')
                    AND r.status NOT IN ('signed', 'declined')
                ORDER BY e.created_at DESC
            """),
            {
                "loan_id": int(loan_id),
                "org_id": int(org_id),
                "email": email_lower,
            },
        ).fetchall()

        pending_list = []
        for row in envelopes:
            is_urgent = False
            if row[5]:  # expires_at
                days_until_expiry = (row[5] - datetime.now(timezone.utc)).days
                is_urgent = days_until_expiry <= 3

            pending_list.append({
                "envelope_id": row[0],
                "envelope_uuid": row[1],
                "title": row[2],
                "envelope_status": row[3],
                "document_name": row[6],
                "recipient_id": row[7],
                "recipient_status": row[8],
                "signing_url": row[9],
                "viewed_at": row[10].isoformat() if row[10] else None,
                "signed_at": row[11].isoformat() if row[11] else None,
                "auth_method": row[12],
                "created_at": row[4].isoformat() if row[4] else None,
                "expires_at": row[5].isoformat() if row[5] else None,
                "is_urgent": is_urgent,
                "action_label": _get_translation("signature_pending", lang),
            })

        return {
            "loan_id": loan_id,
            "pending_count": len(pending_list),
            "signatures": pending_list,
            "lang": lang,
        }

    # -----------------------------------------------------------------------
    # Portal Analytics
    # -----------------------------------------------------------------------

    async def get_portal_analytics(
        self,
        loan_id: str,
        org_id: str,
    ) -> Dict[str, Any]:
        """
        Get portal analytics for a loan (login frequency, upload patterns,
        completion rates).

        Args:
            loan_id: Loan ID.
            org_id: Organization ID.

        Returns:
            Dict with analytics metrics.
        """
        # Login frequency
        login_stats = self.db.execute(
            sa_text("""
                SELECT
                    COUNT(*) AS total_logins,
                    MAX(created_at) AS last_login,
                    COUNT(DISTINCT DATE(created_at)) AS unique_login_days
                FROM portal_analytics_events
                WHERE loan_id = :loan_id
                    AND org_id = :org_id
                    AND event_type = 'portal_login'
            """),
            {"loan_id": int(loan_id), "org_id": int(org_id)},
        ).fetchone()

        # Upload patterns
        upload_stats = self.db.execute(
            sa_text("""
                SELECT
                    COUNT(*) AS total_uploads,
                    COUNT(CASE WHEN metadata->>'camera_capture' = 'True' THEN 1 END) AS camera_uploads,
                    COUNT(CASE WHEN metadata->>'upload_source' = 'MOBILE' THEN 1 END) AS mobile_uploads,
                    MAX(created_at) AS last_upload
                FROM portal_analytics_events
                WHERE loan_id = :loan_id
                    AND org_id = :org_id
                    AND event_type = 'document_uploaded'
            """),
            {"loan_id": int(loan_id), "org_id": int(org_id)},
        ).fetchone()

        # Completion rate (from checklist)
        checklist_stats = self.db.execute(
            sa_text("""
                SELECT
                    COUNT(*) AS total_requests,
                    COUNT(CASE WHEN status IN ('ACCEPTED', 'WAIVED') THEN 1 END) AS completed_requests
                FROM smart_document_requests
                WHERE loan_id = :loan_id AND is_active = true
            """),
            {"loan_id": int(loan_id)},
        ).fetchone()

        total_req = checklist_stats[0] if checklist_stats else 0
        completed_req = checklist_stats[1] if checklist_stats else 0

        return {
            "loan_id": loan_id,
            "login_frequency": {
                "total_logins": login_stats[0] if login_stats else 0,
                "last_login": login_stats[1].isoformat() if login_stats and login_stats[1] else None,
                "unique_login_days": login_stats[2] if login_stats else 0,
            },
            "upload_patterns": {
                "total_uploads": upload_stats[0] if upload_stats else 0,
                "camera_uploads": upload_stats[1] if upload_stats else 0,
                "mobile_uploads": upload_stats[2] if upload_stats else 0,
                "last_upload": upload_stats[3].isoformat() if upload_stats and upload_stats[3] else None,
            },
            "completion_rates": {
                "total_items": total_req,
                "completed_items": completed_req,
                "completion_pct": round((completed_req / total_req) * 100) if total_req else 0,
            },
        }

    # -----------------------------------------------------------------------
    # White-Label / Branding
    # -----------------------------------------------------------------------

    async def _get_org_branding(self, org_id: Any) -> Dict[str, Any]:
        """
        Get organization branding for the portal (white-label support).

        Returns logo URL, primary/accent colors, tagline, and custom CSS.
        """
        org = self.db.execute(
            sa_text("""
                SELECT
                    name, slug,
                    booking_logo_url, booking_primary_color,
                    booking_accent_color, booking_tagline,
                    booking_custom_css, booking_cover_image_url
                FROM organizations
                WHERE id = :org_id
            """),
            {"org_id": int(org_id)},
        ).fetchone()

        if not org:
            return {
                "org_name": "Perennia",
                "logo_url": None,
                "primary_color": "#1a73e8",
                "accent_color": "#34a853",
                "tagline": None,
                "custom_css": None,
                "cover_image_url": None,
            }

        return {
            "org_name": org[0],
            "org_slug": org[1],
            "logo_url": org[2],
            "primary_color": org[3] or "#1a73e8",
            "accent_color": org[4] or "#34a853",
            "tagline": org[5],
            "custom_css": org[6],
            "cover_image_url": org[7],
        }

    # -----------------------------------------------------------------------
    # Internal Helpers
    # -----------------------------------------------------------------------

    async def _verify_borrower_on_loan(
        self,
        borrower_email: str,
        loan_id: int,
        org_id: int,
    ) -> Dict[str, Any]:
        """
        Verify that a borrower email is associated with a loan in the org.

        Checks the loan's borrower_email and co_borrower_email fields.

        Raises:
            ValueError: If borrower not found on loan.
        """
        loan = self.db.execute(
            sa_text("""
                SELECT
                    l.borrower_name, l.borrower_email, l.co_borrower_email,
                    l.coborrower_name
                FROM loans l
                WHERE l.id = :loan_id AND l.organization_id = :org_id
            """),
            {"loan_id": loan_id, "org_id": org_id},
        ).fetchone()

        if not loan:
            raise ValueError("Loan not found")

        # Check if email matches borrower or co-borrower
        loan_borrower_email = (loan[1] or "").strip().lower()
        loan_coborrower_email = (loan[2] or "").strip().lower()
        email_lower = borrower_email.strip().lower()

        if email_lower == loan_borrower_email:
            return {"name": loan[0] or "", "role": "borrower"}
        elif email_lower == loan_coborrower_email:
            return {"name": loan[3] or "", "role": "co_borrower"}
        else:
            raise ValueError("Email not associated with this loan")

    async def _get_recent_activities(
        self,
        loan_id: str,
        limit: int = 10,
    ) -> List[Dict[str, Any]]:
        """Get recent activities for a loan (borrower-safe info only)."""
        try:
            activities = self.db.execute(
                sa_text("""
                    SELECT type, content, created_at
                    FROM activities
                    WHERE loan_id = :loan_id
                    ORDER BY created_at DESC
                    LIMIT :limit
                """),
                {"loan_id": int(loan_id), "limit": limit},
            ).fetchall()

            return [
                {
                    "type": row[0],
                    "description": (row[1] or "")[:200],
                    "date": row[2].isoformat() if row[2] else None,
                }
                for row in activities
            ]
        except Exception as e:
            logger.warning(f"Failed to fetch activities for loan {loan_id}: {e}")
            return []

    def _calculate_progress_pct(self, current_stage: str) -> int:
        """Calculate loan progress percentage based on current stage."""
        stage_progress = {
            "APPLICATION": 5,
            "DISCLOSED": 10,
            "PROCESSING": 20,
            "SUBMITTED": 35,
            "UNDERWRITING": 40,
            "UW_RECEIVED": 45,
            "CONDITIONAL_APPROVAL": 55,
            "APPROVED": 65,
            "SUSPENDED": 40,
            "CTC": 75,
            "CLEAR_TO_CLOSE": 75,
            "CLOSING": 80,
            "DOCS": 85,
            "DOCS_OUT": 90,
            "FUNDED": 100,
            "CANCELLED": 0,
            "DENIED": 0,
            "DEAD": 0,
            "WITHDRAWN": 0,
            "DOES_NOT_QUALIFY": 0,
        }
        return stage_progress.get(current_stage, 0)

    async def _log_portal_event(
        self,
        loan_id: str,
        org_id: str,
        event_type: str,
        borrower_email: str,
        metadata: Optional[Dict] = None,
    ) -> None:
        """Log a portal analytics event."""
        try:
            import json
            self.db.execute(
                sa_text("""
                    INSERT INTO portal_analytics_events (
                        loan_id, org_id, event_type, borrower_email,
                        metadata, created_at
                    ) VALUES (
                        :loan_id, :org_id, :event_type, :borrower_email,
                        :metadata, :created_at
                    )
                """),
                {
                    "loan_id": int(loan_id),
                    "org_id": int(org_id),
                    "event_type": event_type,
                    "borrower_email": borrower_email.strip().lower(),
                    "metadata": json.dumps(metadata or {}),
                    "created_at": datetime.now(timezone.utc),
                },
            )
            self.db.commit()
        except Exception as e:
            # Analytics logging should never fail the main operation
            logger.warning(f"Failed to log portal event: {e}")


# ---------------------------------------------------------------------------
# Factory / Singleton
# ---------------------------------------------------------------------------

_service_instance: Optional[BorrowerPortalV2Service] = None


def get_borrower_portal_v2_service(db: Session) -> BorrowerPortalV2Service:
    """
    Get or create the BorrowerPortalV2Service instance.

    The service is created per-request since it holds a DB session reference.
    """
    return BorrowerPortalV2Service(db)
