"""
Smart Docs Income Calculation Sub-package

Specialized income calculation services for mortgage underwriting.
"""

from services.smart_docs.income.commission_income_service import (
    CommissionIncomeService,
    get_commission_income_service,
    CommissionIncomeResult,
    CommissionSource,
    TrendAnalysis,
    ExpenseAnalysis,
    EligibilityResult,
    CalculationMethod,
)

from services.smart_docs.income.rental_income_service import (
    RentalIncomeService,
    get_rental_income_service,
    RentalIncomeResult,
    PropertyRentalResult,
    ScheduleEResult,
    ProposedRentalResult,
    PITIAOffsetResult,
    ExperienceValidation,
    DepositCrossReference,
    PropertyData,
    ScheduleELineItems,
    LeaseData,
    RentalIncomeMethod,
    LoanProgram,
    PropertyRole,
)

from services.smart_docs.income.dti_optimizer_service import (
    DTIOptimizerService,
    get_dti_optimizer_service,
    DTIResult,
    PITIABreakdown,
    DebtItem,
    IncomeSource as DTIIncomeSource,
    OptimizationScenario,
    CompensatingFactor,
    ComplianceResult as DTIComplianceResult,
    ResidualResult,
    AgencyDTILimit,
    LoanProgram as DTILoanProgram,
    AGENCY_LIMITS,
)

from services.smart_docs.income.retirement_income_service import (
    RetirementIncomeService,
    get_retirement_income_service,
    RetirementIncomeResult,
    RetirementIncomeSourceResult,
    RetirementIncomeSource,
    RetirementAccount,
    ContinuanceResult,
    GrossUpResult,
    DepletionResult,
    DepletionAccountResult,
    DocRequirement,
    ValidationFlag,
    RetirementIncomeType,
    ContinuanceStatus,
    AccountType,
)

from services.smart_docs.income.asset_depletion_service import (
    AssetDepletionService,
    get_asset_depletion_service,
    AssetDepletionResult,
    AssetAccount,
    EligibilityResult as AssetEligibilityResult,
    DiscountedAssets,
    DiscountedAccount,
    SustainabilityResult,
    TaxImpactAnalysis,
    AgencyRules,
    AccountType as AssetAccountType,
    OwnershipType,
    AgencyType,
    SustainabilityRating,
)

from services.smart_docs.income.employment_gap_service import (
    EmploymentGapService,
    get_employment_gap_service,
    EmploymentAnalysis,
    EmploymentGap,
    EmploymentRecord,
    GapEvaluation,
    GapClassification,
    GapReason,
    ReasonAcceptability,
    EmploymentTransition,
    ContinuityAssessment,
    ContinuityRating,
    ReturnToWorkAssessment,
    ConcurrentEmployment,
    DocRequirement as GapDocRequirement,
)

from services.smart_docs.income.non_traditional_income_service import (
    NonTraditionalIncomeService,
    get_non_traditional_income_service,
    NonTraditionalIncomeType,
    ContinuanceRisk,
    QualifyingStatus,
    DocumentationCompleteness,
    DocRequirement as NTDocRequirement,
    IncomeClassification,
    TrendAnalysis as NTTrendAnalysis,
    ExpenseAnalysis as NTExpenseAnalysis,
    GigIncomeResult,
    SeasonalResult,
    ForeignIncomeResult,
    ValidationResult as NTValidationResult,
    ContinuanceResult as NTContinuanceResult,
)

from services.smart_docs.income.income_trending_service import (
    IncomeTrendingService,
    get_income_trending_service,
    TrendAnalysis as IncomeTrendAnalysis,
    TrendClassification,
    IncomePrediction,
    ReconciliationResult,
    ReconciliationDiscrepancy,
    SourceTrend,
    IncomeDataPoint,
    IncomeAlert,
    ChartData,
    ChartDataSeries,
    SeasonalPattern,
    TrendLine,
    DeclineAction,
    AlertSeverity as IncomeTrendAlertSeverity,
)

__all__ = [
    # Commission income
    "CommissionIncomeService",
    "get_commission_income_service",
    "CommissionIncomeResult",
    "CommissionSource",
    "TrendAnalysis",
    "ExpenseAnalysis",
    "EligibilityResult",
    "CalculationMethod",
    # Rental income
    "RentalIncomeService",
    "get_rental_income_service",
    "RentalIncomeResult",
    "PropertyRentalResult",
    "ScheduleEResult",
    "ProposedRentalResult",
    "PITIAOffsetResult",
    "ExperienceValidation",
    "DepositCrossReference",
    "PropertyData",
    "ScheduleELineItems",
    "LeaseData",
    "RentalIncomeMethod",
    "LoanProgram",
    "PropertyRole",
    # DTI optimizer
    "DTIOptimizerService",
    "get_dti_optimizer_service",
    "DTIResult",
    "PITIABreakdown",
    "DebtItem",
    "DTIIncomeSource",
    "OptimizationScenario",
    "CompensatingFactor",
    "DTIComplianceResult",
    "ResidualResult",
    "AgencyDTILimit",
    "DTILoanProgram",
    "AGENCY_LIMITS",
    # Retirement income
    "RetirementIncomeService",
    "get_retirement_income_service",
    "RetirementIncomeResult",
    "RetirementIncomeSourceResult",
    "RetirementIncomeSource",
    "RetirementAccount",
    "ContinuanceResult",
    "GrossUpResult",
    "DepletionResult",
    "DepletionAccountResult",
    "DocRequirement",
    "ValidationFlag",
    "RetirementIncomeType",
    "ContinuanceStatus",
    "AccountType",
    # Asset depletion income
    "AssetDepletionService",
    "get_asset_depletion_service",
    "AssetDepletionResult",
    "AssetAccount",
    "AssetEligibilityResult",
    "DiscountedAssets",
    "DiscountedAccount",
    "SustainabilityResult",
    "TaxImpactAnalysis",
    "AgencyRules",
    "AssetAccountType",
    "OwnershipType",
    "AgencyType",
    "SustainabilityRating",
    # Employment gap analysis
    "EmploymentGapService",
    "get_employment_gap_service",
    "EmploymentAnalysis",
    "EmploymentGap",
    "EmploymentRecord",
    "GapEvaluation",
    "GapClassification",
    "GapReason",
    "ReasonAcceptability",
    "EmploymentTransition",
    "ContinuityAssessment",
    "ContinuityRating",
    "ReturnToWorkAssessment",
    "ConcurrentEmployment",
    "GapDocRequirement",
    # Non-traditional income
    "NonTraditionalIncomeService",
    "get_non_traditional_income_service",
    "NonTraditionalIncomeType",
    "ContinuanceRisk",
    "QualifyingStatus",
    "DocumentationCompleteness",
    "NTDocRequirement",
    "IncomeClassification",
    "NTTrendAnalysis",
    "NTExpenseAnalysis",
    "GigIncomeResult",
    "SeasonalResult",
    "ForeignIncomeResult",
    "NTValidationResult",
    "NTContinuanceResult",
    # Income trending & prediction
    "IncomeTrendingService",
    "get_income_trending_service",
    "IncomeTrendAnalysis",
    "TrendClassification",
    "IncomePrediction",
    "ReconciliationResult",
    "ReconciliationDiscrepancy",
    "SourceTrend",
    "IncomeDataPoint",
    "IncomeAlert",
    "ChartData",
    "ChartDataSeries",
    "SeasonalPattern",
    "TrendLine",
    "DeclineAction",
    "IncomeTrendAlertSeverity",
]
