import React from 'react';
import { sanitizeHTML } from '../../utils/sanitize';

/**
 * CallDraftsTab - Email drafts generated by AI Scribe during calls.
 * Shows draft list and detail panel with send/delete actions.
 */
export default function CallDraftsTab({
  callDrafts,
  callDraftsLoading,
  selectedDraft,
  setSelectedDraft,
  handleSendDraft,
  handleDeleteDraft,
  draftActionLoading,
}) {
  if (callDraftsLoading) {
    return (
      <div className="empty-state">
        <div className="spinner-small"></div>
        <p>Loading call drafts...</p>
      </div>
    );
  }

  if (callDrafts.length === 0) {
    return (
      <div className="empty-state">
        <div className="empty-icon"></div>
        <h2>No Call Drafts</h2>
        <p>Email drafts generated by the AI Scribe during calls will appear here for review and sending.</p>
      </div>
    );
  }

  return (
    <div className="reconciliation-content">
      <div className="items-list">
        {callDrafts.map((draft) => (
          <div
            key={draft.id}
            className={`reconciliation-item ${selectedDraft?.id === draft.id ? 'selected' : ''}`}
            onClick={() => setSelectedDraft(draft)}
          >
            <div className="item-content">
              <div className="item-header">
                <div className="item-category">EMAIL DRAFT</div>
                <div className="status-badge pending">DRAFT</div>
              </div>
              <div className="item-subject">{draft.subject || '(No subject)'}</div>
              <div className="item-meta">
                <span className="meta-sender">To: {draft.recipient_email || 'Unknown'}</span>
                <span className="meta-date">
                  {draft.created_at ? new Date(draft.created_at).toLocaleString('en-US', {
                    month: 'short', day: 'numeric', year: 'numeric',
                    hour: 'numeric', minute: '2-digit', hour12: true
                  }) : 'N/A'}
                </span>
              </div>
              {draft.recipient_name && (
                <div className="item-match">Recipient: {draft.recipient_name}</div>
              )}
            </div>
          </div>
        ))}
      </div>

      {selectedDraft && (
        <div className="detail-panel">
          <div className="panel-header">
            <h2>Email Draft</h2>
            <button className="close-panel" onClick={() => setSelectedDraft(null)}>&#10005;</button>
          </div>

          <div className="email-context">
            <h3>Draft Details</h3>
            <div className="context-field">
              <strong>To:</strong> {selectedDraft.recipient_name} &lt;{selectedDraft.recipient_email}&gt;
            </div>
            <div className="context-field">
              <strong>Subject:</strong> {selectedDraft.subject}
            </div>
            {selectedDraft.cc_emails?.length > 0 && (
              <div className="context-field">
                <strong>CC:</strong> {selectedDraft.cc_emails.join(', ')}
              </div>
            )}
            <div className="context-field">
              <strong>Source:</strong> Call Recording
            </div>
            <div className="context-field">
              <strong>Created:</strong> {selectedDraft.created_at ? new Date(selectedDraft.created_at).toLocaleString() : 'N/A'}
            </div>
          </div>

          <div className="extracted-fields">
            <h3>Email Body</h3>
            <div style={{
              padding: '16px',
              background: '#f9fafb',
              borderRadius: '8px',
              border: '1px solid #e5e7eb',
              whiteSpace: 'pre-wrap',
              lineHeight: '1.6',
              fontSize: '14px'
            }}>
              {selectedDraft.body_html ? (
                <div dangerouslySetInnerHTML={{ __html: sanitizeHTML(selectedDraft.body_html, { allowedTags: ['p', 'br', 'b', 'i', 'strong', 'em', 'a', 'div', 'span', 'table', 'tr', 'td', 'th', 'tbody', 'thead', 'hr', 'ul', 'ol', 'li', 'h1', 'h2', 'h3', 'h4', 'blockquote'] }) }} />
              ) : (
                selectedDraft.body_text || '(No content)'
              )}
            </div>
          </div>

          {selectedDraft.call_summary && (
            <div className="ai-info" style={{ marginTop: '16px' }}>
              <h3>Call Summary</h3>
              <p>{selectedDraft.call_summary}</p>
            </div>
          )}

          <div className="action-buttons" style={{ marginTop: '20px', display: 'flex', gap: '12px' }}>
            <button
              className="approve-button"
              onClick={() => handleSendDraft(selectedDraft.id)}
              disabled={draftActionLoading === selectedDraft.id}
            >
              {draftActionLoading === selectedDraft.id ? 'Sending...' : 'Send Email'}
            </button>
            <button
              className="reject-button"
              onClick={() => handleDeleteDraft(selectedDraft.id)}
              disabled={draftActionLoading === selectedDraft.id}
            >
              Delete
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
